In [72]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
label = {'BENIGN':1, 'PortScan':2, 'Bot':3, 'DDoS':4} 

In [7]:
loaded_train_CICIDS2017 = pd.read_csv('dataset/train_CICIDS2017.csv')
loaded_test_CICIDS2017 = pd.read_csv('dataset/test_CICIDS2017.csv')

In [8]:
loaded_train_CICIDS2017['Label'].value_counts()

BENIGN      1589847
PortScan     111245
DDoS          89668
Bot            1338
Name: Label, dtype: int64

In [9]:
loaded_train_CICIDS2017.Label = [label[item] for item in loaded_train_CICIDS2017.Label] 

In [10]:
loaded_train_CICIDS2017['Label'].value_counts()

1    1589847
2     111245
4      89668
3       1338
Name: Label, dtype: int64

In [11]:
loaded_test_CICIDS2017['Label'].value_counts()

BENIGN      681473
PortScan     47595
DDoS         38357
Bot            618
Name: Label, dtype: int64

In [12]:
loaded_test_CICIDS2017.Label = [label[item] for item in loaded_test_CICIDS2017.Label] 

In [13]:
loaded_test_CICIDS2017['Label'].value_counts()

1    681473
2     47595
4     38357
3       618
Name: Label, dtype: int64

In [14]:
load_X_CICIDS2017_train = loaded_train_CICIDS2017.drop(["Label"],axis=1)
load_X_CICIDS2017_test = loaded_test_CICIDS2017.drop(["Label"],axis=1)
Y_CICIDS2017_train = loaded_train_CICIDS2017["Label"]
Y_CICIDS2017_test = loaded_test_CICIDS2017["Label"]

In [15]:
scaler_CICIDS2017 = StandardScaler()
X_CICIDS2017_train = scaler_CICIDS2017.fit_transform(load_X_CICIDS2017_train)
X_CICIDS2017_test = scaler_CICIDS2017.fit_transform(load_X_CICIDS2017_test)

In [16]:
loaded_train_CICIDS2018 = pd.read_csv('dataset/train_CICIDS2018.csv')
loaded_test_CICIDS2018 = pd.read_csv('dataset/test_CICIDS2018.csv')

In [17]:
loaded_train_CICIDS2018['Label'].value_counts()

Benign                    9373028
DDOS attack-HOIC           480155
DDoS attacks-LOIC-HTTP     403452
Bot                        200433
PortScan                   112426
DDOS attack-LOIC-UDP         1214
Name: Label, dtype: int64

In [18]:
loaded_train_CICIDS2018['Label'] = loaded_train_CICIDS2018['Label'].str.replace('Benign', 'BENIGN')

In [19]:
loaded_train_CICIDS2018['Label'] = loaded_train_CICIDS2018['Label'].str.replace('DDOS attack-HOIC', 'DDoS')

In [20]:
loaded_train_CICIDS2018['Label'] = loaded_train_CICIDS2018['Label'].str.replace('DDoS attacks-LOIC-HTTP', 'DDoS')

In [21]:
loaded_train_CICIDS2018['Label'] = loaded_train_CICIDS2018['Label'].str.replace('DDOS attack-LOIC-UDP', 'DDoS')

In [22]:
loaded_train_CICIDS2018['Label'].value_counts()

BENIGN      9373028
DDoS         884821
Bot          200433
PortScan     112426
Name: Label, dtype: int64

In [23]:
loaded_test_CICIDS2018['Label'].value_counts()

Benign                    4017221
DDOS attack-HOIC           205857
DDoS attacks-LOIC-HTTP     172739
Bot                         85758
PortScan                    48213
DDOS attack-LOIC-UDP          516
Name: Label, dtype: int64

In [24]:
loaded_test_CICIDS2018['Label'] = loaded_test_CICIDS2018['Label'].str.replace('Benign', 'BENIGN')

In [25]:
loaded_test_CICIDS2018['Label'] = loaded_test_CICIDS2018['Label'].str.replace('DDOS attack-HOIC', 'DDoS')

In [26]:
loaded_test_CICIDS2018['Label'] = loaded_test_CICIDS2018['Label'].str.replace('DDoS attacks-LOIC-HTTP', 'DDoS')

In [27]:
loaded_test_CICIDS2018['Label'] = loaded_test_CICIDS2018['Label'].str.replace('DDOS attack-LOIC-UDP', 'DDoS')

In [28]:
loaded_test_CICIDS2018['Label'].value_counts()

BENIGN      4017221
DDoS         379112
Bot           85758
PortScan      48213
Name: Label, dtype: int64

In [29]:
loaded_train_CICIDS2018.Label = [label[item] for item in loaded_train_CICIDS2018.Label] 

In [30]:
loaded_train_CICIDS2018['Label'].value_counts()

1    9373028
4     884821
3     200433
2     112426
Name: Label, dtype: int64

In [31]:
loaded_test_CICIDS2018['Label'].value_counts()

BENIGN      4017221
DDoS         379112
Bot           85758
PortScan      48213
Name: Label, dtype: int64

In [32]:
loaded_test_CICIDS2018.Label = [label[item] for item in loaded_test_CICIDS2018.Label] 

In [33]:
loaded_test_CICIDS2018['Label'].value_counts()

1    4017221
4     379112
3      85758
2      48213
Name: Label, dtype: int64

In [34]:
load_X_CICIDS2018_train = loaded_train_CICIDS2018.drop(["Label"],axis=1)
load_X_CICIDS2018_test = loaded_test_CICIDS2018.drop(["Label"],axis=1)
Y_CICIDS2018_train = loaded_train_CICIDS2018["Label"]
Y_CICIDS2018_test = loaded_test_CICIDS2018["Label"]

In [35]:
scaler_CICIDS2018 = StandardScaler()
X_CICIDS2018_train = scaler_CICIDS2018.fit_transform(load_X_CICIDS2018_train)
X_CICIDS2018_test = scaler_CICIDS2018.fit_transform(load_X_CICIDS2018_test)

In [36]:
loaded_train_CICToNIoT = pd.read_csv('dataset/train_CICToNIoT.csv')
loaded_test_CICToNIoT = pd.read_csv('dataset/test_CICToNIoT.csv')

In [37]:
loaded_train_CICToNIoT['Label'].value_counts()

BENIGN      1759990
PortScan      25180
Bot           18998
DDoS            159
Name: Label, dtype: int64

In [38]:
loaded_train_CICToNIoT.Label = [label[item] for item in loaded_train_CICToNIoT.Label] 

In [39]:
loaded_train_CICToNIoT['Label'].value_counts()

1    1759990
2      25180
3      18998
4        159
Name: Label, dtype: int64

In [40]:
loaded_test_CICToNIoT['Label'].value_counts()

BENIGN      754069
PortScan     11025
Bot           8147
DDoS            43
Name: Label, dtype: int64

In [41]:
loaded_test_CICToNIoT.Label = [label[item] for item in loaded_test_CICToNIoT.Label] 

In [42]:
loaded_test_CICToNIoT['Label'].value_counts()

1    754069
2     11025
3      8147
4        43
Name: Label, dtype: int64

In [43]:
load_X_CICToNIoT_train = loaded_train_CICToNIoT.drop(["Label"],axis=1)
load_X_CICToNIoT_test = loaded_test_CICToNIoT.drop(["Label"],axis=1)
Y_CICToNIoT_train = loaded_train_CICToNIoT["Label"]
Y_CICToNIoT_test = loaded_test_CICToNIoT["Label"]

In [44]:
scaler_CICToNIoT = StandardScaler()
X_CICToNIoT_train = scaler_CICToNIoT.fit_transform(load_X_CICToNIoT_train)
X_CICToNIoT_test = scaler_CICToNIoT.fit_transform(load_X_CICToNIoT_test)

In [45]:
loaded_train_CICBotIoT = pd.read_csv('dataset/train_CICBotIoT.csv')
loaded_test_CICBotIoT = pd.read_csv('dataset/test_CICBotIoT.csv')

In [46]:
loaded_train_CICBotIoT['Label'].value_counts()

DDoS        3440817
PortScan    2458168
BENIGN        62593
Bot            1164
Name: Label, dtype: int64

In [47]:
loaded_train_CICBotIoT.Label = [label[item] for item in loaded_train_CICBotIoT.Label] 

In [48]:
loaded_train_CICBotIoT['Label'].value_counts()

4    3440817
2    2458168
1      62593
3       1164
Name: Label, dtype: int64

In [49]:
loaded_test_CICBotIoT['Label'].value_counts()

DDoS        1473043
PortScan    1055240
BENIGN        26641
Bot             537
Name: Label, dtype: int64

In [50]:
loaded_test_CICBotIoT.Label = [label[item] for item in loaded_test_CICBotIoT.Label] 

In [51]:
loaded_test_CICBotIoT['Label'].value_counts()

4    1473043
2    1055240
1      26641
3        537
Name: Label, dtype: int64

In [52]:
load_X_CICBotIoT_train = loaded_train_CICBotIoT.drop(["Label"],axis=1)
load_X_CICBotIoT_test = loaded_test_CICBotIoT.drop(["Label"],axis=1)
Y_CICBotIoT_train = loaded_train_CICBotIoT["Label"]
Y_CICBotIoT_test = loaded_test_CICBotIoT["Label"]

In [53]:
scaler_CICBotIoT = StandardScaler()
X_CICBotIoT_train = scaler_CICBotIoT.fit_transform(load_X_CICBotIoT_train)
X_CICBotIoT_test = scaler_CICBotIoT.fit_transform(load_X_CICBotIoT_test)

In [54]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

2023-08-16 21:23:58.277422: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 21:23:59.325765: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 21:23:59.328835: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-16 21:24:03.088569: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [55]:
from keras.metrics import Recall, Precision

In [56]:
import keras.backend as K
import tensorflow as tf

def f1_score(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    recall = true_positives / (possible_positives + K.epsilon())
    f1_val = 2*(precision*recall)/(precision+recall+K.epsilon())
    return f1_val

In [53]:
def fit_model_CICIDS2017(trainX1, trainy1):
    model1 = Sequential()
    model1.add(Dense(13, input_dim=77, activation='relu'))
    model1.add(Dense(11, activation='relu'))
    model1.add(Dense(9, activation='relu'))
    model1.add(Dense(7, activation='relu'))
    model1.add(Dense(4, activation='softmax')) 
    model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy', Recall(), Precision(), f1_score])
    
    model1.fit(trainX1, trainy1, epochs=10, batch_size=1000, verbose=1)
    return model1

In [54]:
def fit_model_CICIDS2018(trainX2, trainy2):
    model2 = Sequential()
    model2.add(Dense(13, input_dim=77, activation='relu'))
    model2.add(Dense(11, activation='relu'))
    model2.add(Dense(9, activation='relu'))
    model2.add(Dense(7, activation='relu'))
    model2.add(Dense(4, activation='softmax')) 
    model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy', Recall(), Precision(), f1_score])
    
    model2.fit(trainX2, trainy2, epochs=10, batch_size=1000, verbose=1)
    return model2

In [55]:
def fit_model_CICToNIoT(trainX3, trainy3):
    model3 = Sequential()
    model3.add(Dense(13, input_dim=77, activation='relu'))
    model3.add(Dense(11, activation='relu'))
    model3.add(Dense(9, activation='relu'))
    model3.add(Dense(7, activation='relu'))
    model3.add(Dense(4, activation='softmax')) 
    model3.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy', Recall(), Precision(), f1_score])
    
    model3.fit(trainX3, trainy3, epochs=10, batch_size=1000, verbose=1)
    return model3

In [56]:
def fit_model_CICBotIoT(trainX4, trainy4):
    model4 = Sequential()
    model4.add(Dense(13, input_dim=77, activation='relu'))
    model4.add(Dense(11, activation='relu'))
    model4.add(Dense(9, activation='relu'))
    model4.add(Dense(7, activation='relu'))
    model4.add(Dense(4, activation='softmax')) 
    model4.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy', Recall(), Precision(), f1_score])
    
    model4.fit(trainX4, trainy4, epochs=10, batch_size=1000, verbose=1)
    return model4

In [57]:
encoder_Y_train_CICIDS2017 = LabelEncoder()
encoder_Y_train_CICIDS2017.fit(Y_CICIDS2017_train)
transform_Y_train_CICIDS2017 = encoder_Y_train_CICIDS2017.transform(Y_CICIDS2017_train)
encoded_Y_train_CICIDS2017 = to_categorical(transform_Y_train_CICIDS2017, num_classes=4)
print(encoded_Y_train_CICIDS2017)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [58]:
encoder_Y_test_CICIDS2017 = LabelEncoder()
encoder_Y_test_CICIDS2017.fit(Y_CICIDS2017_test)
transform_Y_test_CICIDS2017 = encoder_Y_test_CICIDS2017.transform(Y_CICIDS2017_test)
encoded_Y_test_CICIDS2017 = to_categorical(transform_Y_test_CICIDS2017, num_classes=4)
print(encoded_Y_test_CICIDS2017)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [60]:
model_CICIDS2017 = fit_model_CICIDS2017(X_CICIDS2017_train, encoded_Y_train_CICIDS2017)

filename_CICIDS2017 = 'models/model_CICIDS2017.h5'
model_CICIDS2017.save(filename_CICIDS2017)
print('>Saved %s' % filename_CICIDS2017)

Epoch 1/10
1793/1793 [==============================] - 9s 4ms/step - loss: 0.1027 - accuracy: 0.9629 - recall: 0.9423 - precision: 0.9734 - f1_score: 0.9449
Epoch 2/10
1793/1793 [==============================] - 7s 4ms/step - loss: 0.0346 - accuracy: 0.9873 - recall: 0.9871 - precision: 0.9874 - f1_score: 0.9873
Epoch 3/10
1793/1793 [==============================] - 7s 4ms/step - loss: 0.0319 - accuracy: 0.9884 - recall: 0.9883 - precision: 0.9884 - f1_score: 0.9884
Epoch 4/10
1793/1793 [==============================] - 7s 4ms/step - loss: 0.0301 - accuracy: 0.9887 - recall: 0.9886 - precision: 0.9887 - f1_score: 0.9887
Epoch 5/10
1793/1793 [==============================] - 7s 4ms/step - loss: 0.0286 - accuracy: 0.9891 - recall: 0.9890 - precision: 0.9891 - f1_score: 0.9891
Epoch 6/10
1793/1793 [==============================] - 7s 4ms/step - loss: 0.0269 - accuracy: 0.9895 - recall: 0.9895 - precision: 0.9895 - f1_score: 0.9895
Epoch 7/10
1793/1793 [==============================

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [59]:
encoder_Y_train_CICIDS2018 = LabelEncoder()
encoder_Y_train_CICIDS2018.fit(Y_CICIDS2018_train)
transform_Y_train_CICIDS2018 = encoder_Y_train_CICIDS2018.transform(Y_CICIDS2018_train)
encoded_Y_train_CICIDS2018 = to_categorical(transform_Y_train_CICIDS2018, num_classes=4)
print(encoded_Y_train_CICIDS2018)

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [60]:
encoder_Y_test_CICIDS2018 = LabelEncoder()
encoder_Y_test_CICIDS2018.fit(Y_CICIDS2018_test)
transform_Y_test_CICIDS2018 = encoder_Y_test_CICIDS2018.transform(Y_CICIDS2018_test)
encoded_Y_test_CICIDS2018 = to_categorical(transform_Y_test_CICIDS2018, num_classes=4)
print(encoded_Y_test_CICIDS2018)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [67]:
model_CICIDS2018 = fit_model_CICIDS2018(X_CICIDS2018_train, encoded_Y_train_CICIDS2018)

filename_CICIDS2018 = 'models/model_CICIDS2018.h5'
model_CICIDS2018.save(filename_CICIDS2018)
print('>Saved %s' % filename_CICIDS2018)

Epoch 1/10
10571/10571 [==============================] - 44s 4ms/step - loss: 0.0744 - accuracy: 0.9830 - recall_1: 0.9780 - precision_1: 0.9858 - f1_score: 0.9801
Epoch 2/10
10571/10571 [==============================] - 42s 4ms/step - loss: 0.0523 - accuracy: 0.9885 - recall_1: 0.9885 - precision_1: 0.9886 - f1_score: 0.9886
Epoch 3/10
10571/10571 [==============================] - 42s 4ms/step - loss: 0.0515 - accuracy: 0.9886 - recall_1: 0.9886 - precision_1: 0.9886 - f1_score: 0.9886
Epoch 4/10
10571/10571 [==============================] - 42s 4ms/step - loss: 0.0511 - accuracy: 0.9886 - recall_1: 0.9886 - precision_1: 0.9886 - f1_score: 0.9887
Epoch 5/10
10571/10571 [==============================] - 42s 4ms/step - loss: 0.0509 - accuracy: 0.9886 - recall_1: 0.9886 - precision_1: 0.9887 - f1_score: 0.9887
Epoch 6/10
10571/10571 [==============================] - 42s 4ms/step - loss: 0.0507 - accuracy: 0.9887 - recall_1: 0.9887 - precision_1: 0.9887 - f1_score: 0.9887
Epoch 7/10

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [61]:
encoder_Y_train_CICToNIoT = LabelEncoder()
encoder_Y_train_CICToNIoT.fit(Y_CICToNIoT_train)
transform_Y_train_CICToNIoT = encoder_Y_train_CICToNIoT.transform(Y_CICToNIoT_train)
encoded_Y_train_CICToNIoT = to_categorical(transform_Y_train_CICToNIoT, num_classes=4)
print(encoded_Y_train_CICToNIoT)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [62]:
encoder_Y_test_CICToNIoT = LabelEncoder()
encoder_Y_test_CICToNIoT.fit(Y_CICToNIoT_test)
transform_Y_test_CICToNIoT = encoder_Y_test_CICToNIoT.transform(Y_CICToNIoT_test)
encoded_Y_test_CICToNIoT = to_categorical(transform_Y_test_CICToNIoT, num_classes=4)
print(encoded_Y_test_CICToNIoT)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [70]:
model_CICToNIoT = fit_model_CICToNIoT(X_CICToNIoT_train, encoded_Y_train_CICToNIoT)

filename_CICToNIoT = 'models/model_CICToNIoT.h5'
model_CICToNIoT.save(filename_CICToNIoT)
print('>Saved %s' % filename_CICToNIoT)

Epoch 1/10
1805/1805 [==============================] - 8s 4ms/step - loss: 0.0685 - accuracy: 0.9805 - recall_2: 0.9618 - precision_2: 0.9890 - f1_score: 0.9676
Epoch 2/10
1805/1805 [==============================] - 7s 4ms/step - loss: 0.0169 - accuracy: 0.9918 - recall_2: 0.9917 - precision_2: 0.9918 - f1_score: 0.9918
Epoch 3/10
1805/1805 [==============================] - 7s 4ms/step - loss: 0.0151 - accuracy: 0.9925 - recall_2: 0.9925 - precision_2: 0.9925 - f1_score: 0.9925
Epoch 4/10
1805/1805 [==============================] - 7s 4ms/step - loss: 0.0143 - accuracy: 0.9930 - recall_2: 0.9930 - precision_2: 0.9930 - f1_score: 0.9930
Epoch 5/10
1805/1805 [==============================] - 7s 4ms/step - loss: 0.0138 - accuracy: 0.9933 - recall_2: 0.9933 - precision_2: 0.9933 - f1_score: 0.9933
Epoch 6/10
1805/1805 [==============================] - 7s 4ms/step - loss: 0.0134 - accuracy: 0.9937 - recall_2: 0.9937 - precision_2: 0.9937 - f1_score: 0.9937
Epoch 7/10
1805/1805 [======

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [63]:
encoder_Y_train_CICBotIoT = LabelEncoder()
encoder_Y_train_CICBotIoT.fit(Y_CICBotIoT_train)
transform_Y_train_CICBotIoT = encoder_Y_train_CICBotIoT.transform(Y_CICBotIoT_train)
encoded_Y_train_CICBotIoT = to_categorical(transform_Y_train_CICBotIoT, num_classes=4)
print(encoded_Y_train_CICBotIoT)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [64]:
encoder_Y_test_CICBotIoT = LabelEncoder()
encoder_Y_test_CICBotIoT.fit(Y_CICBotIoT_test)
transform_Y_test_CICBotIoT = encoder_Y_test_CICBotIoT.transform(Y_CICBotIoT_test)
encoded_Y_test_CICBotIoT = to_categorical(transform_Y_test_CICBotIoT, num_classes=4)
print(encoded_Y_test_CICBotIoT)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [73]:
model_CICBotIoT = fit_model_CICBotIoT(X_CICBotIoT_train, encoded_Y_train_CICBotIoT)

filename_CICBotIoT = 'models/model_CICBotIoT.h5'
model_CICBotIoT.save(filename_CICBotIoT)
print('>Saved %s' % filename_CICBotIoT)

Epoch 1/10
5963/5963 [==============================] - 25s 4ms/step - loss: 0.2788 - accuracy: 0.8741 - recall_3: 0.8627 - precision_3: 0.8779 - f1_score: 0.8650
Epoch 2/10
5963/5963 [==============================] - 24s 4ms/step - loss: 0.2461 - accuracy: 0.8829 - recall_3: 0.8826 - precision_3: 0.8831 - f1_score: 0.8829
Epoch 3/10
5963/5963 [==============================] - 23s 4ms/step - loss: 0.2413 - accuracy: 0.8851 - recall_3: 0.8850 - precision_3: 0.8852 - f1_score: 0.8851
Epoch 4/10
5963/5963 [==============================] - 24s 4ms/step - loss: 0.2387 - accuracy: 0.8865 - recall_3: 0.8865 - precision_3: 0.8866 - f1_score: 0.8865
Epoch 5/10
5963/5963 [==============================] - 23s 4ms/step - loss: 0.2373 - accuracy: 0.8873 - recall_3: 0.8872 - precision_3: 0.8873 - f1_score: 0.8872
Epoch 6/10
5963/5963 [==============================] - 23s 4ms/step - loss: 0.2361 - accuracy: 0.8879 - recall_3: 0.8878 - precision_3: 0.8879 - f1_score: 0.8878
Epoch 7/10
5963/5963 [

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [65]:
from keras.models import load_model

In [66]:
filename_model_CICIDS2017 = 'models/model_CICIDS2017.h5'
loaded_model_CICIDS2017 = load_model(filename_model_CICIDS2017, custom_objects={"f1_score": f1_score})

In [67]:
filename_model_CICIDS2018 = 'models/model_CICIDS2018.h5'
loaded_model_CICIDS2018 = load_model(filename_model_CICIDS2018, custom_objects={"f1_score": f1_score})

In [68]:
filename_model_CICToNIoT = 'models/model_CICToNIoT.h5'
loaded_model_CICToNIoT = load_model(filename_model_CICToNIoT, custom_objects={"f1_score": f1_score})

In [69]:
filename_model_CICBotIoT = 'models/model_CICBotIoT.h5'
loaded_model_CICBotIoT = load_model(filename_model_CICBotIoT, custom_objects={"f1_score": f1_score})

In [70]:
all_models = []
all_models.append(loaded_model_CICIDS2017)
all_models.append(loaded_model_CICIDS2018)
all_models.append(loaded_model_CICToNIoT)
all_models.append(loaded_model_CICBotIoT)

print(all_models)

[<keras.src.engine.sequential.Sequential object at 0x7effac2c8d00>, <keras.src.engine.sequential.Sequential object at 0x7eff456ab760>, <keras.src.engine.sequential.Sequential object at 0x7efe9bae2b90>, <keras.src.engine.sequential.Sequential object at 0x7eff456aaaa0>]


In [71]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [81]:
pred_ConNN_CICIDS2017 = loaded_model_CICIDS2017.predict(X_CICIDS2017_test)
print(pred_ConNN_CICIDS2017)

24002/24002 [==============================] - 40s 2ms/step
[[9.99999940e-01 1.05286725e-23 1.21112212e-15 1.59925479e-26]
 [9.97505605e-01 2.12739178e-05 2.46969052e-03 3.42402518e-06]
 [1.94364344e-04 2.85584993e-16 2.63271893e-09 9.99805689e-01]
 ...
 [1.00000000e+00 4.40811870e-15 1.67897884e-09 5.44682147e-11]
 [9.81941998e-01 1.48796316e-04 9.73542966e-03 8.17371253e-03]
 [9.99628782e-01 1.45506283e-06 3.68243636e-04 1.60693173e-06]]


In [72]:
print(encoded_Y_test_CICIDS2017)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [73]:
argmax_Y_test_CICIDS2017 = np.argmax(encoded_Y_test_CICIDS2017, axis=1)
print(argmax_Y_test_CICIDS2017)

[0 0 3 ... 0 0 0]


In [84]:
argmax_pred_ConNN_CICIDS2017 = np.argmax(pred_ConNN_CICIDS2017, axis=1)
print(argmax_Y_test_CICIDS2017)

[0 0 3 ... 0 0 0]


In [85]:
acc_pred_ConNN_CICIDS2017 = accuracy_score(argmax_Y_test_CICIDS2017, argmax_pred_ConNN_CICIDS2017)
print('Test Accuracy CICIDS2017: %.3f' % acc_pred_ConNN_CICIDS2017)
pre_mac_pred_ConNN_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017, argmax_pred_ConNN_CICIDS2017, average = 'macro')
print('Macro Test Precision CICIDS2017: %.3f' % pre_mac_pred_ConNN_CICIDS2017)
rec_mac_pred_ConNN_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017, argmax_pred_ConNN_CICIDS2017, average = 'macro')
print('Macro Test Recall CICIDS2017: %.3f' % rec_mac_pred_ConNN_CICIDS2017)
f1_mac_pred_ConNN_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017, argmax_pred_ConNN_CICIDS2017, average = 'macro')
print('Macro Test F1 CICIDS2017: %.3f' % f1_mac_pred_ConNN_CICIDS2017)
pre_mic_pred_ConNN_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017, argmax_pred_ConNN_CICIDS2017, average = 'micro')
print('Micro Test Precision CICIDS2017: %.3f' % pre_mic_pred_ConNN_CICIDS2017)
rec_mic_pred_ConNN_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017, argmax_pred_ConNN_CICIDS2017, average = 'micro')
print('Micro Test Recall CICIDS2017: %.3f' % rec_mic_pred_ConNN_CICIDS2017)
f1_mic_pred_ConNN_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017, argmax_pred_ConNN_CICIDS2017, average = 'micro')
print('Micro Test F1 CICIDS2017: %.3f' % f1_mic_pred_ConNN_CICIDS2017)

Test Accuracy CICIDS2017: 0.986
Macro Test Precision CICIDS2017: 0.886
Macro Test Recall CICIDS2017: 0.819
Macro Test F1 CICIDS2017: 0.829
Micro Test Precision CICIDS2017: 0.986
Micro Test Recall CICIDS2017: 0.986
Micro Test F1 CICIDS2017: 0.986


In [86]:
pred_ConNN_CICIDS2018 = loaded_model_CICIDS2018.predict(X_CICIDS2018_test)
print(pred_ConNN_CICIDS2018)

141572/141572 [==============================] - 237s 2ms/step
[[9.9677956e-01 3.2095280e-03 7.9344491e-12 1.0953031e-05]
 [9.9591279e-01 4.0871906e-03 2.7865404e-11 4.8728521e-10]
 [9.8651719e-01 1.3482727e-02 2.4262077e-12 2.2693912e-26]
 ...
 [9.9314082e-01 6.8136267e-03 2.3468303e-07 4.5191755e-05]
 [9.9392897e-01 6.0544480e-03 1.9587732e-07 1.6288635e-05]
 [9.8956442e-01 1.0435593e-02 1.2315776e-11 6.3229726e-21]]


In [74]:
print(encoded_Y_test_CICIDS2018)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [75]:
argmax_Y_test_CICIDS2018 = np.argmax(encoded_Y_test_CICIDS2018, axis=1)
print(argmax_Y_test_CICIDS2018)

[0 0 0 ... 0 0 0]


In [89]:
argmax_pred_ConNN_CICIDS2018 = np.argmax(pred_ConNN_CICIDS2018, axis=1)
print(argmax_Y_test_CICIDS2018)

[0 0 0 ... 0 0 0]


In [90]:
acc_pred_ConNN_CICIDS2018 = accuracy_score(argmax_Y_test_CICIDS2018, argmax_pred_ConNN_CICIDS2018)
print('Test Accuracy CICIDS2018: %.3f' % acc_pred_ConNN_CICIDS2018)
pre_mac_pred_ConNN_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018, argmax_pred_ConNN_CICIDS2018, average = 'macro')
print('Macro Test Precision CICIDS2018: %.3f' % pre_mac_pred_ConNN_CICIDS2018)
rec_mac_pred_ConNN_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018, argmax_pred_ConNN_CICIDS2018, average = 'macro')
print('Macro Test Recall CICIDS2018: %.3f' % rec_mac_pred_ConNN_CICIDS2018)
f1_mac_pred_ConNN_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018, argmax_pred_ConNN_CICIDS2018, average = 'macro')
print('Macro Test F1 CICIDS2018: %.3f' % f1_mac_pred_ConNN_CICIDS2018)
pre_mic_pred_ConNN_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018, argmax_pred_ConNN_CICIDS2018, average = 'micro')
print('Micro Test Precision CICIDS2018: %.3f' % pre_mic_pred_ConNN_CICIDS2018)
rec_mic_pred_ConNN_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018, argmax_pred_ConNN_CICIDS2018, average = 'micro')
print('Micro Test Recall CICIDS2018: %.3f' % rec_mic_pred_ConNN_CICIDS2018)
f1_mic_pred_ConNN_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018, argmax_pred_ConNN_CICIDS2018, average = 'micro')
print('Micro Test F1 CICIDS2018: %.3f' % f1_mic_pred_ConNN_CICIDS2018)

Test Accuracy CICIDS2018: 0.887
Macro Test Precision CICIDS2018: 0.556
Macro Test Recall CICIDS2018: 0.251
Macro Test F1 CICIDS2018: 0.238
Micro Test Precision CICIDS2018: 0.887
Micro Test Recall CICIDS2018: 0.887
Micro Test F1 CICIDS2018: 0.887


In [73]:
pred_ConNN_CICToNIoT = loaded_model_CICToNIoT.predict(X_CICToNIoT_test)
print(pred_ConNN_CICToNIoT)

24166/24166 [==============================] - 48s 2ms/step
[[9.9999863e-01 1.9054578e-08 1.2937918e-06 9.6406139e-10]
 [9.9999994e-01 2.9568076e-15 3.0716100e-11 2.1651504e-18]
 [9.9999994e-01 7.8567579e-16 1.9374696e-11 7.4528761e-19]
 ...
 [9.9995291e-01 1.0136134e-06 4.5717301e-05 1.8971089e-07]
 [9.9999881e-01 1.0616228e-10 1.1614943e-06 1.7965621e-12]
 [1.0000000e+00 7.2296352e-13 7.3887507e-10 7.5579040e-16]]


In [74]:
print(encoded_Y_test_CICToNIoT)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [75]:
argmax_Y_test_CICToNIoT = np.argmax(encoded_Y_test_CICToNIoT, axis=1)
print(argmax_Y_test_CICToNIoT)

[0 0 0 ... 0 0 0]


In [76]:
argmax_pred_ConNN_CICToNIoT = np.argmax(pred_ConNN_CICToNIoT, axis=1)
print(argmax_Y_test_CICToNIoT)

[0 0 0 ... 0 0 0]


In [77]:
acc_pred_ConNN_CICToNIoT = accuracy_score(argmax_Y_test_CICToNIoT, argmax_pred_ConNN_CICToNIoT)
print('Test Accuracy CICToNIoT: %.3f' % acc_pred_ConNN_CICToNIoT)
pre_mac_pred_ConNN_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT, argmax_pred_ConNN_CICToNIoT, average = 'macro')
print('Macro Test Precision CICToNIoT: %.3f' % pre_mac_pred_ConNN_CICToNIoT)
rec_mac_pred_ConNN_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT, argmax_pred_ConNN_CICToNIoT, average = 'macro')
print('Macro Test Recall CICToNIoT: %.3f' % rec_mac_pred_ConNN_CICToNIoT)
f1_mac_pred_ConNN_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT, argmax_pred_ConNN_CICToNIoT, average = 'macro')
print('Macro Test F1 CICToNIoT: %.3f' % f1_mac_pred_ConNN_CICToNIoT)
pre_mic_pred_ConNN_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT, argmax_pred_ConNN_CICToNIoT, average = 'micro')
print('Micro Test Precision CICToNIoT: %.3f' % pre_mic_pred_ConNN_CICToNIoT)
rec_mic_pred_ConNN_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT, argmax_pred_ConNN_CICToNIoT, average = 'micro')
print('Micro Test Recall CICToNIoT: %.3f' % rec_mic_pred_ConNN_CICToNIoT)
f1_mic_pred_ConNN_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT, argmax_pred_ConNN_CICToNIoT, average = 'micro')
print('Micro Test F1 CICToNIoT: %.3f' % f1_mic_pred_ConNN_CICToNIoT)

Test Accuracy CICToNIoT: 0.988
Macro Test Precision CICToNIoT: 0.837
Macro Test Recall CICToNIoT: 0.757
Macro Test F1 CICToNIoT: 0.767
Micro Test Precision CICToNIoT: 0.988
Micro Test Recall CICToNIoT: 0.988
Micro Test F1 CICToNIoT: 0.988


In [96]:
pred_ConNN_CICBotIoT = loaded_model_CICBotIoT.predict(X_CICBotIoT_test)
print(pred_ConNN_CICBotIoT)

79859/79859 [==============================] - 133s 2ms/step
[[3.75356066e-11 2.03819317e-03 2.15817391e-08 9.97961640e-01]
 [5.44615114e-06 9.99994457e-01 1.06943547e-08 2.07999798e-11]
 [7.49855147e-08 6.93707526e-01 1.51479835e-05 3.06277305e-01]
 ...
 [3.26348081e-11 1.99144986e-03 1.98223429e-08 9.98008549e-01]
 [5.94222256e-05 2.44154297e-02 1.94090593e-04 9.75331068e-01]
 [1.31162966e-03 9.97580767e-01 1.10649865e-03 1.22894812e-06]]


In [78]:
print(encoded_Y_test_CICBotIoT)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [79]:
argmax_Y_test_CICBotIoT = np.argmax(encoded_Y_test_CICBotIoT, axis=1)
print(argmax_Y_test_CICBotIoT)

[3 1 1 ... 3 3 1]


In [99]:
argmax_pred_ConNN_CICBotIoT = np.argmax(pred_ConNN_CICBotIoT, axis=1)
print(argmax_Y_test_CICBotIoT)

[3 1 1 ... 3 3 1]


In [100]:
acc_pred_ConNN_CICBotIoT = accuracy_score(argmax_Y_test_CICBotIoT, argmax_pred_ConNN_CICBotIoT)
print('Test Accuracy CICBotIoT: %.3f' % acc_pred_ConNN_CICBotIoT)
pre_mac_pred_ConNN_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT, argmax_pred_ConNN_CICBotIoT, average = 'macro')
print('Macro Test Precision CICBotIoT: %.3f' % pre_mac_pred_ConNN_CICBotIoT)
rec_mac_pred_ConNN_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT, argmax_pred_ConNN_CICBotIoT, average = 'macro')
print('Macro Test Recall CICBotIoT: %.3f' % rec_mac_pred_ConNN_CICBotIoT)
f1_mac_pred_ConNN_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT, argmax_pred_ConNN_CICBotIoT, average = 'macro')
print('Macro Test F1 CICBotIoT: %.3f' % f1_mac_pred_ConNN_CICBotIoT)
pre_mic_pred_ConNN_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT, argmax_pred_ConNN_CICBotIoT, average = 'micro')
print('Micro Test Precision CICBotIoT: %.3f' % pre_mic_pred_ConNN_CICBotIoT)
rec_mic_pred_ConNN_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT, argmax_pred_ConNN_CICBotIoT, average = 'micro')
print('Micro Test Recall CICBotIoT: %.3f' % rec_mic_pred_ConNN_CICBotIoT)
f1_mic_pred_ConNN_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT, argmax_pred_ConNN_CICBotIoT, average = 'micro')
print('Micro Test F1 CICBotIoT: %.3f' % f1_mic_pred_ConNN_CICBotIoT)

Test Accuracy CICBotIoT: 0.876
Macro Test Precision CICBotIoT: 0.799
Macro Test Recall CICBotIoT: 0.591
Macro Test F1 CICBotIoT: 0.607
Micro Test Precision CICBotIoT: 0.876
Micro Test Recall CICBotIoT: 0.876
Micro Test F1 CICBotIoT: 0.876


In [80]:
import numpy
from numpy import mean
from numpy import std
from numpy import array
from numpy import argmax

In [85]:
def ensemble_predictions(members, testX):
    yhats = [model.predict(testX) for model in members]
    yhats = array(yhats)
    summed = numpy.sum(yhats, axis=0)
    result = argmax(summed, axis=1)
    return result

In [103]:
pred_NN_CICIDS2017 = ensemble_predictions(all_models, X_CICIDS2017_test)
print(pred_NN_CICIDS2017)

24002/24002 [==============================] - 40s 2ms/step
[0 0 0 ... 0 0 0]


In [104]:
acc_pred_NN_CICIDS2017 = accuracy_score(argmax_Y_test_CICIDS2017, pred_NN_CICIDS2017)
print('Test Accuracy AVGNN CICIDS2017: %.3f' % acc_pred_NN_CICIDS2017)
pre_mac_pred_NN_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017, pred_NN_CICIDS2017, average = 'macro')
print('Macro Test Precision AVGNN CICIDS2017: %.3f' % pre_mac_pred_NN_CICIDS2017)
rec_mac_pred_NN_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017, pred_NN_CICIDS2017, average = 'macro')
print('Macro Test Recall AVGNN CICIDS2017: %.3f' % rec_mac_pred_NN_CICIDS2017)
f1_mac_pred_NN_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017, pred_NN_CICIDS2017, average = 'macro')
print('Macro Test F1 AVGNN CICIDS2017: %.3f' % f1_mac_pred_NN_CICIDS2017)
pre_mic_pred_NN_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017, pred_NN_CICIDS2017, average = 'micro')
print('Micro Test Precision AVGNN CICIDS2017: %.3f' % pre_mic_pred_NN_CICIDS2017)
rec_mic_pred_NN_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017, pred_NN_CICIDS2017, average = 'micro')
print('Micro Test Recall AVGNN CICIDS2017: %.3f' % rec_mic_pred_NN_CICIDS2017)
f1_mic_pred_NN_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017, pred_NN_CICIDS2017, average = 'micro')
print('Micro Test F1 AVGNN CICIDS2017: %.3f' % f1_mic_pred_NN_CICIDS2017)

Test Accuracy AVGNN CICIDS2017: 0.888


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Macro Test Precision AVGNN CICIDS2017: 0.324
Macro Test Recall AVGNN CICIDS2017: 0.257
Macro Test F1 AVGNN CICIDS2017: 0.249
Micro Test Precision AVGNN CICIDS2017: 0.888
Micro Test Recall AVGNN CICIDS2017: 0.888
Micro Test F1 AVGNN CICIDS2017: 0.888


In [105]:
pred_NN_CICIDS2018 = ensemble_predictions(all_models, X_CICIDS2018_test)
print(pred_NN_CICIDS2018)

141572/141572 [==============================] - 230s 2ms/step
[0 0 0 ... 0 0 0]


In [106]:
acc_pred_NN_CICIDS2018 = accuracy_score(argmax_Y_test_CICIDS2018, pred_NN_CICIDS2018)
print('Test Accuracy AVGNN CICIDS2018: %.3f' % acc_pred_NN_CICIDS2018)
pre_mac_pred_NN_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018, pred_NN_CICIDS2018, average = 'macro')
print('Macro Test Precision AVGNN CICIDS2018: %.3f' % pre_mac_pred_NN_CICIDS2018)
rec_mac_pred_NN_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018, pred_NN_CICIDS2018, average = 'macro')
print('Macro Test Recall AVGNN CICIDS2018: %.3f' % rec_mac_pred_NN_CICIDS2018)
f1_mac_pred_NN_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018, pred_NN_CICIDS2018, average = 'macro')
print('Macro Test F1 AVGNN CICIDS2018: %.3f' % f1_mac_pred_NN_CICIDS2018)
pre_mic_pred_NN_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018, pred_NN_CICIDS2018, average = 'micro')
print('Micro Test Precision AVGNN CICIDS2018: %.3f' % pre_mic_pred_NN_CICIDS2018)
rec_mic_pred_NN_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018, pred_NN_CICIDS2018, average = 'micro')
print('Micro Test Recall AVGNN CICIDS2018: %.3f' % rec_mic_pred_NN_CICIDS2018)
f1_mic_pred_NN_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018, pred_NN_CICIDS2018, average = 'micro')
print('Micro Test F1 AVGNN CICIDS2018: %.3f' % f1_mic_pred_NN_CICIDS2018)

Test Accuracy AVGNN CICIDS2018: 0.886
Macro Test Precision AVGNN CICIDS2018: 0.236
Macro Test Recall AVGNN CICIDS2018: 0.251
Macro Test F1 AVGNN CICIDS2018: 0.236
Micro Test Precision AVGNN CICIDS2018: 0.886
Micro Test Recall AVGNN CICIDS2018: 0.886
Micro Test F1 AVGNN CICIDS2018: 0.886


In [107]:
pred_NN_CICToNIoT = ensemble_predictions(all_models, X_CICToNIoT_test)
print(pred_NN_CICToNIoT)

24166/24166 [==============================] - 32s 1ms/step
[0 0 1 ... 0 0 0]


In [108]:
acc_pred_NN_CICToNIoT = accuracy_score(argmax_Y_test_CICToNIoT, pred_NN_CICToNIoT)
print('Test Accuracy AVGNN CICToNIoT: %.3f' % acc_pred_NN_CICToNIoT)
pre_mac_pred_NN_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT, pred_NN_CICToNIoT, average = 'macro')
print('Macro Test Precision AVGNN CICToNIoT: %.3f' % pre_mac_pred_NN_CICToNIoT)
rec_mac_pred_NN_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT, pred_NN_CICToNIoT, average = 'macro')
print('Macro Test Recall AVGNN CICToNIoT: %.3f' % rec_mac_pred_NN_CICToNIoT)
f1_mac_pred_NN_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT, pred_NN_CICToNIoT, average = 'macro')
print('Macro Test F1 AVGNN CICToNIoT: %.3f' % f1_mac_pred_NN_CICToNIoT)
pre_mic_pred_NN_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT, pred_NN_CICToNIoT, average = 'micro')
print('Micro Test Precision AVGNN CICToNIoT: %.3f' % pre_mic_pred_NN_CICToNIoT)
rec_mic_pred_NN_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT, pred_NN_CICToNIoT, average = 'micro')
print('Micro Test Recall AVGNN CICToNIoT: %.3f' % rec_mic_pred_NN_CICToNIoT)
f1_mic_pred_NN_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT, pred_NN_CICToNIoT, average = 'micro')
print('Micro Test F1 AVGNN CICToNIoT: %.3f' % f1_mic_pred_NN_CICToNIoT)

Test Accuracy AVGNN CICToNIoT: 0.892
Macro Test Precision AVGNN CICToNIoT: 0.516
Macro Test Recall AVGNN CICToNIoT: 0.628
Macro Test F1 AVGNN CICToNIoT: 0.369
Micro Test Precision AVGNN CICToNIoT: 0.892
Micro Test Recall AVGNN CICToNIoT: 0.892
Micro Test F1 AVGNN CICToNIoT: 0.892


In [109]:
pred_NN_CICBotIoT = ensemble_predictions(all_models, X_CICBotIoT_test)
print(pred_NN_CICBotIoT)

79859/79859 [==============================] - 107s 1ms/step
[0 1 0 ... 0 0 0]


In [110]:
acc_pred_NN_CICBotIoT = accuracy_score(argmax_Y_test_CICBotIoT, pred_NN_CICBotIoT)
print('Test Accuracy AVGNN CICBotIoT: %.3f' % acc_pred_NN_CICBotIoT)
pre_mac_pred_NN_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT, pred_NN_CICBotIoT, average = 'macro')
print('Macro Test Precision AVGNN CICBotIoT: %.3f' % pre_mac_pred_NN_CICBotIoT)
rec_mac_pred_NN_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT, pred_NN_CICBotIoT, average = 'macro')
print('Macro Test Recall AVGNN CICBotIoT: %.3f' % rec_mac_pred_NN_CICBotIoT)
f1_mac_pred_NN_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT, pred_NN_CICBotIoT, average = 'macro')
print('Macro Test F1 AVGNN CICBotIoT: %.3f' % f1_mac_pred_NN_CICBotIoT)
pre_mic_pred_NN_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT, pred_NN_CICBotIoT, average = 'micro')
print('Micro Test Precision AVGNN CICBotIoT: %.3f' % pre_mic_pred_NN_CICBotIoT)
rec_mic_pred_NN_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT, pred_NN_CICBotIoT, average = 'micro')
print('Micro Test Recall AVGNN CICBotIoT: %.3f' % rec_mic_pred_NN_CICBotIoT)
f1_mic_pred_NN_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT, pred_NN_CICBotIoT, average = 'micro')
print('Micro Test F1 AVGNN CICBotIoT: %.3f' % f1_mic_pred_NN_CICBotIoT)

Test Accuracy AVGNN CICBotIoT: 0.234
Macro Test Precision AVGNN CICBotIoT: 0.460
Macro Test Recall AVGNN CICBotIoT: 0.345
Macro Test F1 AVGNN CICBotIoT: 0.192
Micro Test Precision AVGNN CICBotIoT: 0.234
Micro Test Recall AVGNN CICBotIoT: 0.234
Micro Test F1 AVGNN CICBotIoT: 0.234


In [111]:
pred_CICIDS2017_Cross_CICIDS2018 = loaded_model_CICIDS2017.predict(X_CICIDS2018_test)
print(pred_CICIDS2017_Cross_CICIDS2018)

141572/141572 [==============================] - 212s 1ms/step
[[9.99999702e-01 1.32015158e-25 3.18689116e-15 2.17846321e-07]
 [9.57409143e-01 3.55524750e-18 4.46718967e-10 4.25908752e-02]
 [9.98913109e-01 2.32731804e-06 1.07986724e-03 4.62542857e-06]
 ...
 [9.99999940e-01 9.30437027e-22 2.25261731e-13 3.54120587e-11]
 [9.99999940e-01 3.30115115e-22 1.10503966e-13 9.33285480e-12]
 [9.99837875e-01 1.17138207e-07 1.60303694e-04 1.71075305e-06]]


In [112]:
argmax_pred_CICIDS2017_Cross_CICIDS2018 = np.argmax(pred_CICIDS2017_Cross_CICIDS2018, axis=1)
print(argmax_pred_CICIDS2017_Cross_CICIDS2018)

[0 0 0 ... 0 0 0]


In [113]:
acc_pred_CICIDS2017_Cross_CICIDS2018 = accuracy_score(argmax_Y_test_CICIDS2018,argmax_pred_CICIDS2017_Cross_CICIDS2018)
print('Test Accuracy CICIDS2017 cross CICIDS2018: %.3f' % acc_pred_CICIDS2017_Cross_CICIDS2018)
pre_mac_pred_CICIDS2017_Cross_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018,argmax_pred_CICIDS2017_Cross_CICIDS2018, average = 'macro')
print('Macro Test Precision CICIDS2017 cross CICIDS2018: %.3f' % pre_mac_pred_CICIDS2017_Cross_CICIDS2018)
rec_mac_pred_CICIDS2017_Cross_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018,argmax_pred_CICIDS2017_Cross_CICIDS2018, average = 'macro')
print('Macro Test Recall CICIDS2017 cross CICIDS2018: %.3f' % rec_mac_pred_CICIDS2017_Cross_CICIDS2018)
f1_mac_pred_CICIDS2017_Cross_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018,argmax_pred_CICIDS2017_Cross_CICIDS2018, average = 'macro')
print('Macro Test F1 CICIDS2017 cross CICIDS2018: %.3f' % f1_mac_pred_CICIDS2017_Cross_CICIDS2018)
pre_mic_pred_CICIDS2017_Cross_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018,argmax_pred_CICIDS2017_Cross_CICIDS2018, average = 'micro')
print('Micro Test Precision CICIDS2017 cross CICIDS2018: %.3f' % pre_mic_pred_CICIDS2017_Cross_CICIDS2018)
rec_mic_pred_CICIDS2017_Cross_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018,argmax_pred_CICIDS2017_Cross_CICIDS2018, average = 'micro')
print('Micro Test Recall CICIDS2017 cross CICIDS2018: %.3f' % rec_mic_pred_CICIDS2017_Cross_CICIDS2018)
f1_mic_pred_CICIDS2017_Cross_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018,argmax_pred_CICIDS2017_Cross_CICIDS2018, average = 'micro')
print('Micro Test F1 CICIDS2017 cross CICIDS2018: %.3f' % f1_mic_pred_CICIDS2017_Cross_CICIDS2018)

Test Accuracy CICIDS2017 cross CICIDS2018: 0.879
Macro Test Precision CICIDS2017 cross CICIDS2018: 0.397
Macro Test Recall CICIDS2017 cross CICIDS2018: 0.304
Macro Test F1 CICIDS2017 cross CICIDS2018: 0.324
Micro Test Precision CICIDS2017 cross CICIDS2018: 0.879
Micro Test Recall CICIDS2017 cross CICIDS2018: 0.879
Micro Test F1 CICIDS2017 cross CICIDS2018: 0.879


In [114]:
pred_CICIDS2017_Cross_CICToNIoT = loaded_model_CICIDS2017.predict(X_CICToNIoT_test)
print(pred_CICIDS2017_Cross_CICToNIoT)

24166/24166 [==============================] - 25s 1ms/step
[[3.4033784e-04 0.0000000e+00 8.5563151e-24 9.9965966e-01]
 [6.1415234e-19 9.9999994e-01 0.0000000e+00 3.8732981e-31]
 [5.6770993e-19 9.9999994e-01 0.0000000e+00 3.9210488e-31]
 ...
 [9.9975902e-01 1.4517364e-37 1.9209808e-21 2.4098682e-04]
 [2.4305105e-03 9.9756950e-01 4.9396999e-17 1.0507823e-21]
 [1.5590890e-18 1.0000000e+00 0.0000000e+00 1.8493421e-30]]


In [115]:
argmax_pred_CICIDS2017_Cross_CICToNIoT = np.argmax(pred_CICIDS2017_Cross_CICToNIoT, axis=1)
print(argmax_pred_CICIDS2017_Cross_CICToNIoT)

[3 1 1 ... 0 1 1]


In [116]:
acc_pred_CICIDS2017_Cross_CICToNIoT = accuracy_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2017_Cross_CICToNIoT)
print('Test Accuracy CICIDS2017 cross CICToNIoT: %.3f' % acc_pred_CICIDS2017_Cross_CICToNIoT)
pre_mac_pred_CICIDS2017_Cross_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2017_Cross_CICToNIoT, average = 'macro')
print('Macro Test Precision CICIDS2017 cross CICToNIoT: %.3f' % pre_mac_pred_CICIDS2017_Cross_CICToNIoT)
rec_mac_pred_CICIDS2017_Cross_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2017_Cross_CICToNIoT, average = 'macro')
print('Macro Test Recall CICIDS2017 cross CICToNIoT: %.3f' % rec_mac_pred_CICIDS2017_Cross_CICToNIoT)
f1_mac_pred_CICIDS2017_Cross_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2017_Cross_CICToNIoT, average = 'macro')
print('Macro Test F1 CICIDS2017 cross CICToNIoT: %.3f' % f1_mac_pred_CICIDS2017_Cross_CICToNIoT)
pre_mic_pred_CICIDS2017_Cross_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2017_Cross_CICToNIoT, average = 'micro')
print('Micro Test Precision CICIDS2017 cross CICToNIoT: %.3f' % pre_mic_pred_CICIDS2017_Cross_CICToNIoT)
rec_mic_pred_CICIDS2017_Cross_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2017_Cross_CICToNIoT, average = 'micro')
print('Micro Test Recall CICIDS2017 cross CICToNIoT: %.3f' % rec_mic_pred_CICIDS2017_Cross_CICToNIoT)
f1_mic_pred_CICIDS2017_Cross_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2017_Cross_CICToNIoT, average = 'micro')
print('Micro Test F1 CICIDS2017 cross CICToNIoT: %.3f' % f1_mic_pred_CICIDS2017_Cross_CICToNIoT)

Test Accuracy CICIDS2017 cross CICIDS2018: 0.879
Macro Test Precision CICIDS2017 cross CICIDS2018: 0.397
Macro Test Recall CICIDS2017 cross CICIDS2018: 0.304
Macro Test F1 CICIDS2017 cross CICIDS2018: 0.324
Micro Test Precision CICIDS2017 cross CICIDS2018: 0.879
Micro Test Recall CICIDS2017 cross CICIDS2018: 0.879
Micro Test F1 CICIDS2017 cross CICIDS2018: 0.879


In [117]:
pred_CICIDS2017_Cross_CICBotIoT = loaded_model_CICIDS2017.predict(X_CICBotIoT_test)
print(pred_CICIDS2017_Cross_CICBotIoT)

79859/79859 [==============================] - 115s 1ms/step
[[9.9999994e-01 1.3146784e-11 2.7997048e-08 3.6835246e-17]
 [7.3996745e-19 9.9999994e-01 0.0000000e+00 2.3005905e-34]
 [9.9999696e-01 7.2558057e-09 2.9393700e-06 1.4640980e-12]
 ...
 [1.0000000e+00 1.1077504e-11 2.6774707e-08 5.9070404e-17]
 [9.9999893e-01 1.3545437e-17 1.1785053e-10 1.1039355e-06]
 [3.7398786e-16 1.0000000e+00 0.0000000e+00 1.9503344e-27]]


In [118]:
argmax_pred_CICIDS2017_Cross_CICBotIoT = np.argmax(pred_CICIDS2017_Cross_CICBotIoT, axis=1)
print(argmax_pred_CICIDS2017_Cross_CICBotIoT)

[0 1 0 ... 0 0 1]


In [120]:
acc_pred_CICIDS2017_Cross_CICBotIoT = accuracy_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2017_Cross_CICBotIoT)
print('Test Accuracy CICIDS2017 cross CICBotIoT: %.3f' % acc_pred_CICIDS2017_Cross_CICBotIoT)
pre_mac_pred_CICIDS2017_Cross_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2017_Cross_CICBotIoT, average = 'macro')
print('Macro Test Precision CICIDS2017 cross CICBotIoT: %.3f' % pre_mac_pred_CICIDS2017_Cross_CICBotIoT)
rec_mac_pred_CICIDS2017_Cross_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2017_Cross_CICBotIoT, average = 'macro')
print('Macro Test Recall CICIDS2017 cross CICBotIoT: %.3f' % rec_mac_pred_CICIDS2017_Cross_CICBotIoT)
f1_mac_pred_CICIDS2017_Cross_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2017_Cross_CICBotIoT, average = 'macro')
print('Macro Test F1 CICIDS2017 cross CICBotIoT: %.3f' % f1_mac_pred_CICIDS2017_Cross_CICBotIoT)
pre_mic_pred_CICIDS2017_Cross_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2017_Cross_CICBotIoT, average = 'micro')
print('Micro Test Precision CICIDS2017 cross CICBotIoT: %.3f' % pre_mic_pred_CICIDS2017_Cross_CICBotIoT)
rec_mic_pred_CICIDS2017_Cross_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2017_Cross_CICBotIoT, average = 'micro')
print('Micro Test Recall CICIDS2017 cross CICBotIoT: %.3f' % rec_mic_pred_CICIDS2017_Cross_CICBotIoT)
f1_mic_pred_CICIDS2017_Cross_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2017_Cross_CICBotIoT, average = 'micro')
print('Micro Test F1 CICIDS2017 cross CICBotIoT: %.3f' % f1_mic_pred_CICIDS2017_Cross_CICBotIoT)

Test Accuracy CICIDS2017 cross CICBotIoT: 0.214
Macro Test Precision CICIDS2017 cross CICBotIoT: 0.275
Macro Test Recall CICIDS2017 cross CICBotIoT: 0.193
Macro Test F1 CICIDS2017 cross CICBotIoT: 0.143
Micro Test Precision CICIDS2017 cross CICBotIoT: 0.214
Micro Test Recall CICIDS2017 cross CICBotIoT: 0.214
Micro Test F1 CICIDS2017 cross CICBotIoT: 0.214


In [121]:
pred_CICIDS2018_Cross_CICIDS2017 = loaded_model_CICIDS2018.predict(X_CICIDS2017_test)
print(pred_CICIDS2018_Cross_CICIDS2017)

24002/24002 [==============================] - 44s 2ms/step
[[9.9999994e-01 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [9.8686028e-01 1.3139660e-02 1.0268452e-09 1.2692263e-08]
 [9.5251340e-01 4.7486674e-02 1.1182410e-15 5.3190075e-27]
 ...
 [9.8369437e-01 1.5464693e-02 8.4092387e-04 1.2025973e-08]
 [9.9355656e-01 6.4387373e-03 4.7443027e-06 3.2289844e-09]
 [1.0289666e-01 6.8154940e-03 8.8987410e-01 4.1374165e-04]]


In [122]:
argmax_pred_CICIDS2018_Cross_CICIDS2017 = np.argmax(pred_CICIDS2018_Cross_CICIDS2017, axis=1)
print(argmax_pred_CICIDS2018_Cross_CICIDS2017)

[0 0 0 ... 0 0 2]


In [123]:
acc_pred_CICIDS2018_Cross_CICIDS2017 = accuracy_score(argmax_Y_test_CICIDS2017,argmax_pred_CICIDS2018_Cross_CICIDS2017)
print('Test Accuracy CICIDS2018 cross CICIDS2017: %.3f' % acc_pred_CICIDS2018_Cross_CICIDS2017)
pre_mac_pred_CICIDS2018_Cross_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017,argmax_pred_CICIDS2018_Cross_CICIDS2017, average = 'macro')
print('Macro Test Precision CICIDS2018 cross CICIDS2017: %.3f' % pre_mac_pred_CICIDS2018_Cross_CICIDS2017)
rec_mac_pred_CICIDS2018_Cross_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017,argmax_pred_CICIDS2018_Cross_CICIDS2017, average = 'macro')
print('Macro Test Recall CICIDS2018 cross CICIDS2017: %.3f' % rec_mac_pred_CICIDS2018_Cross_CICIDS2017)
f1_mac_pred_CICIDS2018_Cross_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017,argmax_pred_CICIDS2018_Cross_CICIDS2017, average = 'macro')
print('Macro Test F1 CICIDS2018 cross CICIDS2017: %.3f' % f1_mac_pred_CICIDS2018_Cross_CICIDS2017)
pre_mic_pred_CICIDS2018_Cross_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017,argmax_pred_CICIDS2018_Cross_CICIDS2017, average = 'micro')
print('Micro Test Precision CICIDS2018 cross CICIDS2017: %.3f' % pre_mic_pred_CICIDS2018_Cross_CICIDS2017)
rec_mic_pred_CICIDS2018_Cross_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017,argmax_pred_CICIDS2018_Cross_CICIDS2017, average = 'micro')
print('Micro Test Recall CICIDS2018 cross CICIDS2017: %.3f' % rec_mic_pred_CICIDS2018_Cross_CICIDS2017)
f1_mic_pred_CICIDS2018_Cross_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017,argmax_pred_CICIDS2018_Cross_CICIDS2017, average = 'micro')
print('Micro Test F1 CICIDS2018 cross CICIDS2017: %.3f' % f1_mic_pred_CICIDS2018_Cross_CICIDS2017)

Test Accuracy CICIDS2018 cross CICIDS2017: 0.839
Macro Test Precision CICIDS2018 cross CICIDS2017: 0.227
Macro Test Recall CICIDS2018 cross CICIDS2017: 0.336
Macro Test F1 CICIDS2018 cross CICIDS2017: 0.234
Micro Test Precision CICIDS2018 cross CICIDS2017: 0.839
Micro Test Recall CICIDS2018 cross CICIDS2017: 0.839
Micro Test F1 CICIDS2018 cross CICIDS2017: 0.839


In [124]:
pred_CICIDS2018_Cross_CICToNIoT = loaded_model_CICIDS2018.predict(X_CICToNIoT_test)
print(pred_CICIDS2018_Cross_CICToNIoT)

24166/24166 [==============================] - 39s 2ms/step
[[9.9993128e-01 6.8662419e-05 4.1384554e-22 1.2829306e-12]
 [9.7293699e-01 2.7062973e-02 5.8705839e-11 2.2438558e-09]
 [9.8230338e-01 1.7696543e-02 9.6538298e-11 1.8189125e-09]
 ...
 [9.9844414e-01 1.5545589e-03 6.0046894e-15 1.3550430e-06]
 [9.7670740e-01 2.2618651e-02 6.7387853e-04 6.0294885e-19]
 [9.5274204e-01 4.7257934e-02 2.6087568e-10 7.0246755e-09]]


In [125]:
argmax_pred_CICIDS2018_Cross_CICToNIoT = np.argmax(pred_CICIDS2018_Cross_CICToNIoT, axis=1)
print(argmax_pred_CICIDS2018_Cross_CICToNIoT)

[0 0 0 ... 0 0 0]


In [126]:
acc_pred_CICIDS2018_Cross_CICToNIoT = accuracy_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2018_Cross_CICToNIoT)
print('Test Accuracy CICIDS2018 cross CICToNIoT: %.3f' % acc_pred_CICIDS2018_Cross_CICToNIoT)
pre_mac_pred_CICIDS2018_Cross_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2018_Cross_CICToNIoT, average = 'macro')
print('Macro Test Precision CICIDS2018 cross CICToNIoT: %.3f' % pre_mac_pred_CICIDS2018_Cross_CICToNIoT)
rec_mac_pred_CICIDS2018_Cross_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2018_Cross_CICToNIoT, average = 'macro')
print('Macro Test Recall CICIDS2018 cross CICToNIoT: %.3f' % rec_mac_pred_CICIDS2018_Cross_CICToNIoT)
f1_mac_pred_CICIDS2018_Cross_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2018_Cross_CICToNIoT, average = 'macro')
print('Macro Test F1 CICIDS2018 cross CICToNIoT: %.3f' % f1_mac_pred_CICIDS2018_Cross_CICToNIoT)
pre_mic_pred_CICIDS2018_Cross_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2018_Cross_CICToNIoT, average = 'micro')
print('Micro Test Precision CICIDS2018 cross CICToNIoT: %.3f' % pre_mic_pred_CICIDS2018_Cross_CICToNIoT)
rec_mic_pred_CICIDS2018_Cross_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2018_Cross_CICToNIoT, average = 'micro')
print('Micro Test Recall CICIDS2018 cross CICToNIoT: %.3f' % rec_mic_pred_CICIDS2018_Cross_CICToNIoT)
f1_mic_pred_CICIDS2018_Cross_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT,argmax_pred_CICIDS2018_Cross_CICToNIoT, average = 'micro')
print('Micro Test F1 CICIDS2018 cross CICToNIoT: %.3f' % f1_mic_pred_CICIDS2018_Cross_CICToNIoT)

Test Accuracy CICIDS2018 cross CICToNIoT: 0.973
Macro Test Precision CICIDS2018 cross CICToNIoT: 0.245
Macro Test Recall CICIDS2018 cross CICToNIoT: 0.249
Macro Test F1 CICIDS2018 cross CICToNIoT: 0.247
Micro Test Precision CICIDS2018 cross CICToNIoT: 0.973
Micro Test Recall CICIDS2018 cross CICToNIoT: 0.973
Micro Test F1 CICIDS2018 cross CICToNIoT: 0.973


In [127]:
pred_CICIDS2018_Cross_CICBotIoT = loaded_model_CICIDS2018.predict(X_CICBotIoT_test)
print(pred_CICIDS2018_Cross_CICBotIoT)

79859/79859 [==============================] - 129s 2ms/step
[[9.9999994e-01 5.7406621e-21 0.0000000e+00 0.0000000e+00]
 [9.5147032e-01 4.8529632e-02 6.7264582e-37 0.0000000e+00]
 [9.9236751e-01 7.6323939e-03 1.2471398e-32 0.0000000e+00]
 ...
 [1.0000000e+00 1.3998407e-20 0.0000000e+00 0.0000000e+00]
 [1.0000000e+00 2.6799697e-15 0.0000000e+00 0.0000000e+00]
 [9.9963474e-01 3.6525939e-04 2.7274033e-23 0.0000000e+00]]


In [128]:
argmax_pred_CICIDS2018_Cross_CICBotIoT = np.argmax(pred_CICIDS2018_Cross_CICBotIoT, axis=1)
print(argmax_pred_CICIDS2018_Cross_CICBotIoT)

[0 0 0 ... 0 0 0]


In [129]:
acc_pred_CICIDS2018_Cross_CICBotIoT = accuracy_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2018_Cross_CICBotIoT)
print('Test Accuracy CICIDS2018 cross CICBotIoT: %.3f' % acc_pred_CICIDS2018_Cross_CICBotIoT)
pre_mac_pred_CICIDS2018_Cross_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2018_Cross_CICBotIoT, average = 'macro')
print('Macro Test Precision CICIDS2018 cross CICBotIoT: %.3f' % pre_mac_pred_CICIDS2018_Cross_CICBotIoT)
rec_mac_pred_CICIDS2018_Cross_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2018_Cross_CICBotIoT, average = 'macro')
print('Macro Test Recall CICIDS2018 cross CICBotIoT: %.3f' % rec_mac_pred_CICIDS2018_Cross_CICBotIoT)
f1_mac_pred_CICIDS2018_Cross_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2018_Cross_CICBotIoT, average = 'macro')
print('Macro Test F1 CICIDS2018 cross CICBotIoT: %.3f' % f1_mac_pred_CICIDS2018_Cross_CICBotIoT)
pre_mic_pred_CICIDS2018_Cross_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2018_Cross_CICBotIoT, average = 'micro')
print('Micro Test Precision CICIDS2018 cross CICBotIoT: %.3f' % pre_mic_pred_CICIDS2018_Cross_CICBotIoT)
rec_mic_pred_CICIDS2018_Cross_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2018_Cross_CICBotIoT, average = 'micro')
print('Micro Test Recall CICIDS2018 cross CICBotIoT: %.3f' % rec_mic_pred_CICIDS2018_Cross_CICBotIoT)
f1_mic_pred_CICIDS2018_Cross_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT,argmax_pred_CICIDS2018_Cross_CICBotIoT, average = 'micro')
print('Micro Test F1 CICIDS2018 cross CICBotIoT: %.3f' % f1_mic_pred_CICIDS2018_Cross_CICBotIoT)

Test Accuracy CICIDS2018 cross CICBotIoT: 0.128
Macro Test Precision CICIDS2018 cross CICBotIoT: 0.212
Macro Test Recall CICIDS2018 cross CICBotIoT: 0.228
Macro Test F1 CICIDS2018 cross CICBotIoT: 0.087
Micro Test Precision CICIDS2018 cross CICBotIoT: 0.128
Micro Test Recall CICIDS2018 cross CICBotIoT: 0.128
Micro Test F1 CICIDS2018 cross CICBotIoT: 0.128


In [130]:
pred_CICToNIoT_Cross_CICIDS2017 = loaded_model_CICToNIoT.predict(X_CICIDS2017_test)
print(pred_CICToNIoT_Cross_CICIDS2017)

24002/24002 [==============================] - 32s 1ms/step
[[9.9999994e-01 3.3067610e-10 2.6497265e-08 1.1750114e-11]
 [9.9999791e-01 1.9832783e-06 1.7998291e-12 7.3951522e-17]
 [9.9971557e-01 2.7669340e-04 7.3926685e-06 3.1640403e-07]
 ...
 [5.6574911e-01 4.3425086e-01 1.6529948e-11 5.0419209e-14]
 [9.9953741e-02 9.0004623e-01 5.6449536e-11 2.9112980e-15]
 [1.4284070e-04 9.9985719e-01 3.1793673e-17 2.0295336e-26]]


In [131]:
argmax_pred_CICToNIoT_Cross_CICIDS2017 = np.argmax(pred_CICToNIoT_Cross_CICIDS2017, axis=1)
print(argmax_pred_CICToNIoT_Cross_CICIDS2017)

[0 0 0 ... 0 1 1]


In [132]:
acc_pred_CICToNIoT_Cross_CICIDS2017 = accuracy_score(argmax_Y_test_CICIDS2017,argmax_pred_CICToNIoT_Cross_CICIDS2017)
print('Test Accuracy CICToNIoT cross CICIDS2017: %.3f' % acc_pred_CICToNIoT_Cross_CICIDS2017)
pre_mac_pred_CICToNIoT_Cross_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017,argmax_pred_CICToNIoT_Cross_CICIDS2017, average = 'macro')
print('Macro Test Precision CICToNIoT cross CICIDS2017: %.3f' % pre_mac_pred_CICToNIoT_Cross_CICIDS2017)
rec_mac_pred_CICToNIoT_Cross_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017,argmax_pred_CICToNIoT_Cross_CICIDS2017, average = 'macro')
print('Macro Test Recall CICToNIoT cross CICIDS2017: %.3f' % rec_mac_pred_CICToNIoT_Cross_CICIDS2017)
f1_mac_pred_CICToNIoT_Cross_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017,argmax_pred_CICToNIoT_Cross_CICIDS2017, average = 'macro')
print('Macro Test F1 CICToNIoT cross CICIDS2017: %.3f' % f1_mac_pred_CICToNIoT_Cross_CICIDS2017)
pre_mic_pred_CICToNIoT_Cross_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017,argmax_pred_CICToNIoT_Cross_CICIDS2017, average = 'micro')
print('Micro Test Precision CICToNIoT cross CICIDS2017: %.3f' % pre_mic_pred_CICToNIoT_Cross_CICIDS2017)
rec_mic_pred_CICToNIoT_Cross_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017,argmax_pred_CICToNIoT_Cross_CICIDS2017, average = 'micro')
print('Micro Test Recall CICToNIoT cross CICIDS2017: %.3f' % rec_mic_pred_CICToNIoT_Cross_CICIDS2017)
f1_mic_pred_CICToNIoT_Cross_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017,argmax_pred_CICToNIoT_Cross_CICIDS2017, average = 'micro')
print('Micro Test F1 CICToNIoT cross CICIDS2017: %.3f' % f1_mic_pred_CICToNIoT_Cross_CICIDS2017)

Test Accuracy CICToNIoT cross CICIDS2017: 0.696
Macro Test Precision CICToNIoT cross CICIDS2017: 0.215
Macro Test Recall CICToNIoT cross CICIDS2017: 0.196
Macro Test F1 CICToNIoT cross CICIDS2017: 0.205
Micro Test Precision CICToNIoT cross CICIDS2017: 0.696
Micro Test Recall CICToNIoT cross CICIDS2017: 0.696
Micro Test F1 CICToNIoT cross CICIDS2017: 0.696


In [133]:
pred_CICToNIoT_Cross_CICIDS2018 = loaded_model_CICToNIoT.predict(X_CICIDS2018_test)
print(pred_CICToNIoT_Cross_CICIDS2018)

141572/141572 [==============================] - 230s 2ms/step
[[9.99999940e-01 7.58055828e-34 3.26890327e-25 0.00000000e+00]
 [9.99999940e-01 1.32103543e-22 1.29704526e-17 6.07197924e-29]
 [9.99999940e-01 3.72672371e-21 2.55673613e-16 1.00521544e-25]
 ...
 [9.99999940e-01 1.96583668e-16 6.98855002e-11 1.46636789e-17]
 [9.99999940e-01 4.91706490e-16 1.56855667e-10 2.78447159e-17]
 [9.99999940e-01 5.23602442e-24 1.28648950e-18 1.21019908e-29]]


In [134]:
argmax_pred_CICToNIoT_Cross_CICIDS2018 = np.argmax(pred_CICToNIoT_Cross_CICIDS2018, axis=1)
print(argmax_pred_CICToNIoT_Cross_CICIDS2018)

[0 0 0 ... 0 0 0]


In [135]:
acc_pred_CICToNIoT_Cross_CICIDS2018 = accuracy_score(argmax_Y_test_CICIDS2018,argmax_pred_CICToNIoT_Cross_CICIDS2018)
print('Test Accuracy CICToNIoT cross CICIDS2018: %.3f' % acc_pred_CICToNIoT_Cross_CICIDS2018)
pre_mac_pred_CICToNIoT_Cross_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018,argmax_pred_CICToNIoT_Cross_CICIDS2018, average = 'macro')
print('Macro Test Precision CICToNIoT cross CICIDS2018: %.3f' % pre_mac_pred_CICToNIoT_Cross_CICIDS2018)
rec_mac_pred_CICToNIoT_Cross_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018,argmax_pred_CICToNIoT_Cross_CICIDS2018, average = 'macro')
print('Macro Test Recall CICToNIoT cross CICIDS2018: %.3f' % rec_mac_pred_CICToNIoT_Cross_CICIDS2018)
f1_mac_pred_CICToNIoT_Cross_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018,argmax_pred_CICToNIoT_Cross_CICIDS2018, average = 'macro')
print('Macro Test F1 CICToNIoT cross CICIDS2018: %.3f' % f1_mac_pred_CICToNIoT_Cross_CICIDS2018)
pre_mic_pred_CICToNIoT_Cross_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018,argmax_pred_CICToNIoT_Cross_CICIDS2018, average = 'micro')
print('Micro Test Precision CICToNIoT cross CICIDS2018: %.3f' % pre_mic_pred_CICToNIoT_Cross_CICIDS2018)
rec_mic_pred_CICToNIoT_Cross_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018,argmax_pred_CICToNIoT_Cross_CICIDS2018, average = 'micro')
print('Micro Test Recall CICToNIoT cross CICIDS2018: %.3f' % rec_mic_pred_CICToNIoT_Cross_CICIDS2018)
f1_mic_pred_CICToNIoT_Cross_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018,argmax_pred_CICToNIoT_Cross_CICIDS2018, average = 'micro')
print('Micro Test F1 CICToNIoT cross CICIDS2018: %.3f' % f1_mic_pred_CICToNIoT_Cross_CICIDS2018)

Test Accuracy CICToNIoT cross CICIDS2018: 0.877
Macro Test Precision CICToNIoT cross CICIDS2018: 0.225
Macro Test Recall CICToNIoT cross CICIDS2018: 0.248
Macro Test F1 CICToNIoT cross CICIDS2018: 0.236
Micro Test Precision CICToNIoT cross CICIDS2018: 0.877
Micro Test Recall CICToNIoT cross CICIDS2018: 0.877
Micro Test F1 CICToNIoT cross CICIDS2018: 0.877


In [136]:
pred_CICToNIoT_Cross_CICBotIoT = loaded_model_CICToNIoT.predict(X_CICBotIoT_test)
print(pred_CICToNIoT_Cross_CICBotIoT)

79859/79859 [==============================] - 128s 2ms/step
[[9.9978971e-01 2.1029895e-04 1.9707420e-13 7.5598208e-19]
 [9.9999994e-01 2.5544770e-29 1.5773443e-21 1.6287514e-34]
 [9.9908698e-01 7.1283244e-04 1.8547612e-04 1.4807407e-05]
 ...
 [9.9955350e-01 4.4650474e-04 1.7501419e-13 9.5855375e-19]
 [9.9999917e-01 1.0164748e-09 8.5573112e-07 1.7951831e-11]
 [1.0000000e+00 3.1989966e-09 1.4520645e-14 1.2673418e-18]]


In [137]:
argmax_pred_CICToNIoT_Cross_CICBotIoT = np.argmax(pred_CICToNIoT_Cross_CICBotIoT, axis=1)
print(argmax_pred_CICToNIoT_Cross_CICBotIoT)

[0 0 0 ... 0 0 0]


In [138]:
acc_pred_CICToNIoT_Cross_CICBotIoT = accuracy_score(argmax_Y_test_CICBotIoT,argmax_pred_CICToNIoT_Cross_CICBotIoT)
print('Test Accuracy CICToNIoT cross CICBotIoT: %.3f' % acc_pred_CICToNIoT_Cross_CICBotIoT)
pre_mac_pred_CICToNIoT_Cross_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT,argmax_pred_CICToNIoT_Cross_CICBotIoT, average = 'macro')
print('Macro Test Precision CICToNIoT cross CICBotIoT: %.3f' % pre_mac_pred_CICToNIoT_Cross_CICBotIoT)
rec_mac_pred_CICToNIoT_Cross_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT,argmax_pred_CICToNIoT_Cross_CICBotIoT, average = 'macro')
print('Macro Test Recall CICToNIoT cross CICBotIoT: %.3f' % rec_mac_pred_CICToNIoT_Cross_CICBotIoT)
f1_mac_pred_CICToNIoT_Cross_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT,argmax_pred_CICToNIoT_Cross_CICBotIoT, average = 'macro')
print('Macro Test F1 CICToNIoT cross CICBotIoT: %.3f' % f1_mac_pred_CICToNIoT_Cross_CICBotIoT)
pre_mic_pred_CICToNIoT_Cross_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT,argmax_pred_CICToNIoT_Cross_CICBotIoT, average = 'micro')
print('Micro Test Precision CICToNIoT cross CICBotIoT: %.3f' % pre_mic_pred_CICToNIoT_Cross_CICBotIoT)
rec_mic_pred_CICToNIoT_Cross_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT,argmax_pred_CICToNIoT_Cross_CICBotIoT, average = 'micro')
print('Micro Test Recall CICToNIoT cross CICBotIoT: %.3f' % rec_mic_pred_CICToNIoT_Cross_CICBotIoT)
f1_mic_pred_CICToNIoT_Cross_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT,argmax_pred_CICToNIoT_Cross_CICBotIoT, average = 'micro')
print('Micro Test F1 CICToNIoT cross CICBotIoT: %.3f' % f1_mic_pred_CICToNIoT_Cross_CICBotIoT)

Test Accuracy CICToNIoT cross CICBotIoT: 0.054
Macro Test Precision CICToNIoT cross CICBotIoT: 0.227
Macro Test Recall CICToNIoT cross CICBotIoT: 0.257
Macro Test F1 CICToNIoT cross CICBotIoT: 0.050
Micro Test Precision CICToNIoT cross CICBotIoT: 0.054
Micro Test Recall CICToNIoT cross CICBotIoT: 0.054
Micro Test F1 CICToNIoT cross CICBotIoT: 0.054


In [139]:
pred_CICBotIoT_Cross_CICIDS2017 = loaded_model_CICBotIoT.predict(X_CICIDS2017_test)
print(pred_CICBotIoT_Cross_CICIDS2017)

24002/24002 [==============================] - 41s 2ms/step
[[1.0661808e-12 7.2700167e-01 7.7994123e-08 2.7299821e-01]
 [3.8485166e-03 9.9606067e-01 2.2818249e-05 6.8015208e-05]
 [2.8620954e-04 6.1903417e-01 1.5917803e-03 3.7908792e-01]
 ...
 [4.3105975e-02 2.9739904e-01 6.8620034e-03 6.5263301e-01]
 [9.8867726e-01 6.0817245e-03 2.7782691e-04 4.9632569e-03]
 [9.6511704e-01 3.2351088e-02 6.6495466e-04 1.8669569e-03]]


In [140]:
argmax_pred_CICBotIoT_Cross_CICIDS2017 = np.argmax(pred_CICBotIoT_Cross_CICIDS2017, axis=1)
print(argmax_pred_CICBotIoT_Cross_CICIDS2017)

[1 1 1 ... 3 0 0]


In [141]:
acc_pred_CICBotIoT_Cross_CICIDS2017 = accuracy_score(argmax_Y_test_CICIDS2017,argmax_pred_CICBotIoT_Cross_CICIDS2017)
print('Test Accuracy CICBotIoT cross CICIDS2017: %.3f' % acc_pred_CICBotIoT_Cross_CICIDS2017)
pre_mac_pred_CICBotIoT_Cross_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017,argmax_pred_CICBotIoT_Cross_CICIDS2017, average = 'macro')
print('Macro Test Precision CICBotIoT cross CICIDS2017: %.3f' % pre_mac_pred_CICBotIoT_Cross_CICIDS2017)
rec_mac_pred_CICBotIoT_Cross_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017,argmax_pred_CICBotIoT_Cross_CICIDS2017, average = 'macro')
print('Macro Test Recall CICBotIoT cross CICIDS2017: %.3f' % rec_mac_pred_CICBotIoT_Cross_CICIDS2017)
f1_mac_pred_CICBotIoT_Cross_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017,argmax_pred_CICBotIoT_Cross_CICIDS2017, average = 'macro')
print('Macro Test F1 CICBotIoT cross CICIDS2017: %.3f' % f1_mac_pred_CICBotIoT_Cross_CICIDS2017)
pre_mic_pred_CICBotIoT_Cross_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017,argmax_pred_CICBotIoT_Cross_CICIDS2017, average = 'micro')
print('Micro Test Precision CICBotIoT cross CICIDS2017: %.3f' % pre_mic_pred_CICBotIoT_Cross_CICIDS2017)
rec_mic_pred_CICBotIoT_Cross_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017,argmax_pred_CICBotIoT_Cross_CICIDS2017, average = 'micro')
print('Micro Test Recall CICBotIoT cross CICIDS2017: %.3f' % rec_mic_pred_CICBotIoT_Cross_CICIDS2017)
f1_mic_pred_CICBotIoT_Cross_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017,argmax_pred_CICBotIoT_Cross_CICIDS2017, average = 'micro')
print('Micro Test F1 CICBotIoT cross CICIDS2017: %.3f' % f1_mic_pred_CICBotIoT_Cross_CICIDS2017)

Test Accuracy CICBotIoT cross CICIDS2017: 0.165
Macro Test Precision CICBotIoT cross CICIDS2017: 0.224
Macro Test Recall CICBotIoT cross CICIDS2017: 0.140
Macro Test F1 CICBotIoT cross CICIDS2017: 0.091
Micro Test Precision CICBotIoT cross CICIDS2017: 0.165
Micro Test Recall CICBotIoT cross CICIDS2017: 0.165
Micro Test F1 CICBotIoT cross CICIDS2017: 0.165


In [142]:
pred_CICBotIoT_Cross_CICIDS2018 = loaded_model_CICBotIoT.predict(X_CICIDS2018_test)
print(pred_CICBotIoT_Cross_CICIDS2018)

141572/141572 [==============================] - 218s 2ms/step
[[1.03920974e-01 8.94622624e-01 1.31679396e-03 1.39612384e-04]
 [1.14788723e-04 3.89965087e-01 1.10503368e-03 6.08815074e-01]
 [3.17083985e-01 6.81869268e-01 8.32895923e-04 2.13858249e-04]
 ...
 [1.19173178e-03 4.59062168e-03 1.13290378e-04 9.94104326e-01]
 [3.86305572e-03 3.68030346e-03 1.01878570e-04 9.92354751e-01]
 [4.91136732e-03 9.95062828e-01 1.20473060e-05 1.37622474e-05]]


In [143]:
argmax_pred_CICBotIoT_Cross_CICIDS2018 = np.argmax(pred_CICBotIoT_Cross_CICIDS2018, axis=1)
print(argmax_pred_CICBotIoT_Cross_CICIDS2018)

[1 3 1 ... 3 3 1]


In [144]:
acc_pred_CICBotIoT_Cross_CICIDS2018 = accuracy_score(argmax_Y_test_CICIDS2018,argmax_pred_CICBotIoT_Cross_CICIDS2018)
print('Test Accuracy CICBotIoT cross CICIDS2018: %.3f' % acc_pred_CICBotIoT_Cross_CICIDS2018)
pre_mac_pred_CICBotIoT_Cross_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018,argmax_pred_CICBotIoT_Cross_CICIDS2018, average = 'macro')
print('Macro Test Precision CICBotIoT cross CICIDS2018: %.3f' % pre_mac_pred_CICBotIoT_Cross_CICIDS2018)
rec_mac_pred_CICBotIoT_Cross_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018,argmax_pred_CICBotIoT_Cross_CICIDS2018, average = 'macro')
print('Macro Test Recall CICBotIoT cross CICIDS2018: %.3f' % rec_mac_pred_CICBotIoT_Cross_CICIDS2018)
f1_mac_pred_CICBotIoT_Cross_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018,argmax_pred_CICBotIoT_Cross_CICIDS2018, average = 'macro')
print('Macro Test F1 CICBotIoT cross CICIDS2018: %.3f' % f1_mac_pred_CICBotIoT_Cross_CICIDS2018)
pre_mic_pred_CICBotIoT_Cross_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018,argmax_pred_CICBotIoT_Cross_CICIDS2018, average = 'micro')
print('Micro Test Precision CICBotIoT cross CICIDS2018: %.3f' % pre_mic_pred_CICBotIoT_Cross_CICIDS2018)
rec_mic_pred_CICBotIoT_Cross_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018,argmax_pred_CICBotIoT_Cross_CICIDS2018, average = 'micro')
print('Micro Test Recall CICBotIoT cross CICIDS2018: %.3f' % rec_mic_pred_CICBotIoT_Cross_CICIDS2018)
f1_mic_pred_CICBotIoT_Cross_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018,argmax_pred_CICBotIoT_Cross_CICIDS2018, average = 'micro')
print('Micro Test F1 CICBotIoT cross CICIDS2018: %.3f' % f1_mic_pred_CICBotIoT_Cross_CICIDS2018)

Test Accuracy CICBotIoT cross CICIDS2018: 0.159
Macro Test Precision CICBotIoT cross CICIDS2018: 0.255
Macro Test Recall CICBotIoT cross CICIDS2018: 0.319
Macro Test F1 CICBotIoT cross CICIDS2018: 0.102
Micro Test Precision CICBotIoT cross CICIDS2018: 0.159
Micro Test Recall CICBotIoT cross CICIDS2018: 0.159
Micro Test F1 CICBotIoT cross CICIDS2018: 0.159


In [145]:
pred_CICBotIoT_Cross_CICToNIoT = loaded_model_CICBotIoT.predict(X_CICToNIoT_test)
print(pred_CICBotIoT_Cross_CICToNIoT)

24166/24166 [==============================] - 31s 1ms/step
[[1.69748424e-10 2.99289732e-05 5.85658366e-09 9.99970019e-01]
 [8.15133972e-04 8.43321443e-01 5.41567395e-04 1.55321971e-01]
 [4.92941309e-03 9.85013783e-01 1.82614895e-03 8.23060423e-03]
 ...
 [1.24896253e-08 1.29066117e-03 1.04204969e-06 9.98708248e-01]
 [1.25169195e-02 7.84502149e-01 1.25066936e-03 2.01730311e-01]
 [7.19018044e-06 5.95876127e-02 4.81892675e-05 9.40357029e-01]]


In [147]:
argmax_pred_CICBoTIoT_Cross_CICToNIoT = np.argmax(pred_CICBotIoT_Cross_CICToNIoT, axis=1)
print(argmax_pred_CICBoTIoT_Cross_CICToNIoT)

[3 1 1 ... 3 1 3]


In [150]:
acc_pred_CICBotIoT_Cross_CICToNIoT = accuracy_score(argmax_Y_test_CICToNIoT,argmax_pred_CICBoTIoT_Cross_CICToNIoT)
print('Test Accuracy CICBotIoT cross CICToNIoT: %.3f' % acc_pred_CICBotIoT_Cross_CICToNIoT)
pre_mac_pred_CICBotIoT_Cross_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT,argmax_pred_CICBoTIoT_Cross_CICToNIoT, average = 'macro')
print('Macro Test Precision CICBotIoT cross CICToNIoT: %.3f' % pre_mac_pred_CICBotIoT_Cross_CICToNIoT)
rec_mac_pred_CICBotIoT_Cross_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT,argmax_pred_CICBoTIoT_Cross_CICToNIoT, average = 'macro')
print('Macro Test Recall CICBotIoT cross CICToNIoT: %.3f' % rec_mac_pred_CICBotIoT_Cross_CICToNIoT)
f1_mac_pred_CICBotIoT_Cross_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT,argmax_pred_CICBoTIoT_Cross_CICToNIoT, average = 'macro')
print('Macro Test F1 CICBotIoT cross CICToNIoT: %.3f' % f1_mac_pred_CICBotIoT_Cross_CICToNIoT)
pre_mic_pred_CICBotIoT_Cross_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT,argmax_pred_CICBoTIoT_Cross_CICToNIoT, average = 'micro')
print('Micro Test Precision CICBotIoT cross CICToNIoT: %.3f' % pre_mic_pred_CICBotIoT_Cross_CICToNIoT)
rec_mic_pred_CICBotIoT_Cross_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT,argmax_pred_CICBoTIoT_Cross_CICToNIoT, average = 'micro')
print('Micro Test Recall CICBotIoT cross CICToNIoT: %.3f' % rec_mic_pred_CICBotIoT_Cross_CICToNIoT)
f1_mic_pred_CICBotIoT_Cross_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT,argmax_pred_CICBoTIoT_Cross_CICToNIoT, average = 'micro')
print('Micro Test F1 CICBotIoT cross CICToNIoT: %.3f' % f1_mic_pred_CICBotIoT_Cross_CICToNIoT)

Test Accuracy CICBotIoT cross CICToNIoT: 0.167
Macro Test Precision CICBotIoT cross CICToNIoT: 0.253
Macro Test Recall CICBotIoT cross CICToNIoT: 0.382
Macro Test F1 CICBotIoT cross CICToNIoT: 0.078
Micro Test Precision CICBotIoT cross CICToNIoT: 0.167
Micro Test Recall CICBotIoT cross CICToNIoT: 0.167
Micro Test F1 CICBotIoT cross CICToNIoT: 0.167
