In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
label = {'BENIGN':1, 'PortScan':2, 'Bot':3, 'DDoS':4} 

In [6]:
loaded_test_CICIDS2017 = pd.read_csv('dataset/test_CICIDS2017.csv')

In [7]:
loaded_test_CICIDS2017['Label'].value_counts()

BENIGN      681473
PortScan     47595
DDoS         38357
Bot            618
Name: Label, dtype: int64

In [8]:
loaded_test_CICIDS2017.Label = [label[item] for item in loaded_test_CICIDS2017.Label] 

In [9]:
loaded_test_CICIDS2017['Label'].value_counts()

1    681473
2     47595
4     38357
3       618
Name: Label, dtype: int64

In [10]:
loaded_test_CICIDS2017_m, loaded_test_CICIDS2017_w = train_test_split(loaded_test_CICIDS2017, test_size=0.1, random_state=100)

In [82]:
load_X_CICIDS2017_test = loaded_test_CICIDS2017.drop(["Label"],axis=1)
Y_CICIDS2017_test = loaded_test_CICIDS2017["Label"]
load_X_CICIDS2017_test_w = loaded_test_CICIDS2017_w.drop(["Label"],axis=1)
Y_CICIDS2017_test_w = loaded_test_CICIDS2017_w["Label"]

In [83]:
scaler_CICIDS2017 = StandardScaler()
X_CICIDS2017_test = scaler_CICIDS2017.fit_transform(load_X_CICIDS2017_test)
X_CICIDS2017_test_w = scaler_CICIDS2017.fit_transform(load_X_CICIDS2017_test_w)

In [13]:
loaded_test_CICIDS2018 = pd.read_csv('dataset/test_CICIDS2018.csv')

In [14]:
loaded_test_CICIDS2018['Label'].value_counts()

Benign                    4017221
DDOS attack-HOIC           205857
DDoS attacks-LOIC-HTTP     172739
Bot                         85758
PortScan                    48213
DDOS attack-LOIC-UDP          516
Name: Label, dtype: int64

In [15]:
loaded_test_CICIDS2018['Label'] = loaded_test_CICIDS2018['Label'].str.replace('Benign', 'BENIGN')

In [16]:
loaded_test_CICIDS2018['Label'] = loaded_test_CICIDS2018['Label'].str.replace('DDOS attack-HOIC', 'DDoS')

In [17]:
loaded_test_CICIDS2018['Label'] = loaded_test_CICIDS2018['Label'].str.replace('DDoS attacks-LOIC-HTTP', 'DDoS')

In [18]:
loaded_test_CICIDS2018['Label'] = loaded_test_CICIDS2018['Label'].str.replace('DDOS attack-LOIC-UDP', 'DDoS')

In [19]:
loaded_test_CICIDS2018['Label'].value_counts()

BENIGN      4017221
DDoS         379112
Bot           85758
PortScan      48213
Name: Label, dtype: int64

In [20]:
loaded_test_CICIDS2018['Label'].value_counts()

BENIGN      4017221
DDoS         379112
Bot           85758
PortScan      48213
Name: Label, dtype: int64

In [21]:
loaded_test_CICIDS2018.Label = [label[item] for item in loaded_test_CICIDS2018.Label] 

In [22]:
loaded_test_CICIDS2018['Label'].value_counts()

1    4017221
4     379112
3      85758
2      48213
Name: Label, dtype: int64

In [23]:
loaded_test_CICIDS2018_m, loaded_test_CICIDS2018_w = train_test_split(loaded_test_CICIDS2018, test_size=0.1, random_state=100)

In [84]:
load_X_CICIDS2018_test = loaded_test_CICIDS2018.drop(["Label"],axis=1)
Y_CICIDS2018_test = loaded_test_CICIDS2018["Label"]
load_X_CICIDS2018_test_w = loaded_test_CICIDS2018_w.drop(["Label"],axis=1)
Y_CICIDS2018_test_w = loaded_test_CICIDS2018_w["Label"]

In [85]:
scaler_CICIDS2018 = StandardScaler()
X_CICIDS2018_test = scaler_CICIDS2018.fit_transform(load_X_CICIDS2018_test)
X_CICIDS2018_test_w = scaler_CICIDS2018.fit_transform(load_X_CICIDS2018_test_w)

In [26]:
loaded_test_CICToNIoT = pd.read_csv('dataset/test_CICToNIoT.csv')

In [27]:
loaded_test_CICToNIoT['Label'].value_counts()

BENIGN      754069
PortScan     11025
Bot           8147
DDoS            43
Name: Label, dtype: int64

In [28]:
loaded_test_CICToNIoT.Label = [label[item] for item in loaded_test_CICToNIoT.Label] 

In [29]:
loaded_test_CICToNIoT['Label'].value_counts()

1    754069
2     11025
3      8147
4        43
Name: Label, dtype: int64

In [30]:
loaded_test_CICToNIoT_m, loaded_test_CICToNIoT_w = train_test_split(loaded_test_CICToNIoT, test_size=0.1, random_state=100)

In [86]:
load_X_CICToNIoT_test = loaded_test_CICToNIoT.drop(["Label"],axis=1)
Y_CICToNIoT_test = loaded_test_CICToNIoT["Label"]
load_X_CICToNIoT_test_w = loaded_test_CICToNIoT_w.drop(["Label"],axis=1)
Y_CICToNIoT_test_w = loaded_test_CICToNIoT_w["Label"]

In [87]:
scaler_CICToNIoT = StandardScaler()
X_CICToNIoT_test = scaler_CICToNIoT.fit_transform(load_X_CICToNIoT_test)
X_CICToNIoT_test_w = scaler_CICToNIoT.fit_transform(load_X_CICToNIoT_test_w)

In [33]:
loaded_test_CICBotIoT = pd.read_csv('dataset/test_CICBotIoT.csv')

In [34]:
loaded_test_CICBotIoT['Label'].value_counts()

DDoS        1473043
PortScan    1055240
BENIGN        26641
Bot             537
Name: Label, dtype: int64

In [35]:
loaded_test_CICBotIoT.Label = [label[item] for item in loaded_test_CICBotIoT.Label] 

In [36]:
loaded_test_CICBotIoT['Label'].value_counts()

4    1473043
2    1055240
1      26641
3        537
Name: Label, dtype: int64

In [37]:
loaded_test_CICBotIoT_m, loaded_test_CICBotIoT_w = train_test_split(loaded_test_CICBotIoT, test_size=0.1, random_state=100)

In [88]:
load_X_CICBotIoT_test = loaded_test_CICBotIoT.drop(["Label"],axis=1)
Y_CICBotIoT_test = loaded_test_CICBotIoT["Label"]
load_X_CICBotIoT_test_w = loaded_test_CICBotIoT_w.drop(["Label"],axis=1)
Y_CICBotIoT_test_w = loaded_test_CICBotIoT_w["Label"]

In [89]:
scaler_CICBotIoT = StandardScaler()
X_CICBotIoT_test = scaler_CICBotIoT.fit_transform(load_X_CICBotIoT_test)
X_CICBotIoT_test_w = scaler_CICBotIoT.fit_transform(load_X_CICBotIoT_test_w)

In [40]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

2023-08-16 21:30:44.759306: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 21:30:45.069071: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 21:30:45.071194: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-16 21:30:48.363322: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [41]:
from keras.metrics import Recall, Precision

In [42]:
import keras.backend as K
import tensorflow as tf

def f1_score(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    recall = true_positives / (possible_positives + K.epsilon())
    f1_val = 2*(precision*recall)/(precision+recall+K.epsilon())
    return f1_val

In [90]:
encoder_Y_test_CICIDS2017 = LabelEncoder()
encoder_Y_test_CICIDS2017.fit(Y_CICIDS2017_test)
transform_Y_test_CICIDS2017 = encoder_Y_test_CICIDS2017.transform(Y_CICIDS2017_test)
encoded_Y_test_CICIDS2017 = to_categorical(transform_Y_test_CICIDS2017, num_classes=4)
print(encoded_Y_test_CICIDS2017)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [91]:
encoder_Y_test_CICIDS2017_w = LabelEncoder()
encoder_Y_test_CICIDS2017_w.fit(Y_CICIDS2017_test_w)
transform_Y_test_CICIDS2017_w = encoder_Y_test_CICIDS2017_w.transform(Y_CICIDS2017_test_w)
encoded_Y_test_CICIDS2017_w = to_categorical(transform_Y_test_CICIDS2017_w, num_classes=4)
print(encoded_Y_test_CICIDS2017_w)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [92]:
encoder_Y_test_CICIDS2018 = LabelEncoder()
encoder_Y_test_CICIDS2018.fit(Y_CICIDS2018_test)
transform_Y_test_CICIDS2018 = encoder_Y_test_CICIDS2018.transform(Y_CICIDS2018_test)
encoded_Y_test_CICIDS2018 = to_categorical(transform_Y_test_CICIDS2018, num_classes=4)
print(encoded_Y_test_CICIDS2018)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [93]:
encoder_Y_test_CICIDS2018_w = LabelEncoder()
encoder_Y_test_CICIDS2018_w.fit(Y_CICIDS2018_test_w)
transform_Y_test_CICIDS2018_w = encoder_Y_test_CICIDS2018_w.transform(Y_CICIDS2018_test_w)
encoded_Y_test_CICIDS2018_w = to_categorical(transform_Y_test_CICIDS2018_w, num_classes=4)
print(encoded_Y_test_CICIDS2018_w)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [94]:
encoder_Y_test_CICToNIoT = LabelEncoder()
encoder_Y_test_CICToNIoT.fit(Y_CICToNIoT_test)
transform_Y_test_CICToNIoT = encoder_Y_test_CICToNIoT.transform(Y_CICToNIoT_test)
encoded_Y_test_CICToNIoT = to_categorical(transform_Y_test_CICToNIoT, num_classes=4)
print(encoded_Y_test_CICToNIoT)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [95]:
encoder_Y_test_CICToNIoT_w = LabelEncoder()
encoder_Y_test_CICToNIoT_w.fit(Y_CICToNIoT_test_w)
transform_Y_test_CICToNIoT_w = encoder_Y_test_CICToNIoT_w.transform(Y_CICToNIoT_test_w)
encoded_Y_test_CICToNIoT_w = to_categorical(transform_Y_test_CICToNIoT_w, num_classes=4)
print(encoded_Y_test_CICToNIoT_w)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [96]:
encoder_Y_test_CICBotIoT = LabelEncoder()
encoder_Y_test_CICBotIoT.fit(Y_CICBotIoT_test)
transform_Y_test_CICBotIoT = encoder_Y_test_CICBotIoT.transform(Y_CICBotIoT_test)
encoded_Y_test_CICBotIoT = to_categorical(transform_Y_test_CICBotIoT, num_classes=4)
print(encoded_Y_test_CICBotIoT)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [97]:
encoder_Y_test_CICBotIoT_w = LabelEncoder()
encoder_Y_test_CICBotIoT_w.fit(Y_CICBotIoT_test_w)
transform_Y_test_CICBotIoT_w = encoder_Y_test_CICBotIoT_w.transform(Y_CICBotIoT_test_w)
encoded_Y_test_CICBotIoT_w = to_categorical(transform_Y_test_CICBotIoT_w, num_classes=4)
print(encoded_Y_test_CICBotIoT_w)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [98]:
from keras.models import load_model

In [99]:
filename_model_CICIDS2017 = 'models/model_CICIDS2017.h5'
loaded_model_CICIDS2017 = load_model(filename_model_CICIDS2017, custom_objects={"f1_score": f1_score})

In [100]:
filename_model_CICIDS2018 = 'models/model_CICIDS2018.h5'
loaded_model_CICIDS2018 = load_model(filename_model_CICIDS2018, custom_objects={"f1_score": f1_score})

In [101]:
filename_model_CICToNIoT = 'models/model_CICToNIoT.h5'
loaded_model_CICToNIoT = load_model(filename_model_CICToNIoT, custom_objects={"f1_score": f1_score})

In [102]:
filename_model_CICBotIoT = 'models/model_CICBotIoT.h5'
loaded_model_CICBotIoT = load_model(filename_model_CICBotIoT, custom_objects={"f1_score": f1_score})

In [103]:
all_models = []
all_models.append(loaded_model_CICIDS2017)
all_models.append(loaded_model_CICIDS2018)
all_models.append(loaded_model_CICToNIoT)
all_models.append(loaded_model_CICBotIoT)

print(all_models)

[<keras.src.engine.sequential.Sequential object at 0x7f76c85b5150>, <keras.src.engine.sequential.Sequential object at 0x7f76c85b7760>, <keras.src.engine.sequential.Sequential object at 0x7f76c85b45b0>, <keras.src.engine.sequential.Sequential object at 0x7f76f82dd4e0>]


In [104]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [105]:
print(encoded_Y_test_CICIDS2017)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [106]:
argmax_Y_test_CICIDS2017 = np.argmax(encoded_Y_test_CICIDS2017, axis=1)
print(argmax_Y_test_CICIDS2017)

[0 0 3 ... 0 0 0]


In [107]:
print(encoded_Y_test_CICIDS2017_w)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [108]:
argmax_Y_test_CICIDS2017_w = np.argmax(encoded_Y_test_CICIDS2017_w, axis=1)
print(argmax_Y_test_CICIDS2017_w)

[0 0 0 ... 0 0 0]


In [109]:
print(encoded_Y_test_CICIDS2018)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [110]:
argmax_Y_test_CICIDS2018 = np.argmax(encoded_Y_test_CICIDS2018, axis=1)
print(argmax_Y_test_CICIDS2018)

[0 0 0 ... 0 0 0]


In [111]:
print(encoded_Y_test_CICIDS2018_w)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [112]:
argmax_Y_test_CICIDS2018_w = np.argmax(encoded_Y_test_CICIDS2018_w, axis=1)
print(argmax_Y_test_CICIDS2018_w)

[0 0 0 ... 0 0 0]


In [113]:
print(encoded_Y_test_CICToNIoT)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [114]:
argmax_Y_test_CICToNIoT = np.argmax(encoded_Y_test_CICToNIoT, axis=1)
print(argmax_Y_test_CICToNIoT)

[0 0 0 ... 0 0 0]


In [115]:
print(encoded_Y_test_CICToNIoT_w)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [116]:
argmax_Y_test_CICToNIoT_w = np.argmax(encoded_Y_test_CICToNIoT_w, axis=1)
print(argmax_Y_test_CICToNIoT_w)

[0 0 0 ... 0 0 0]


In [117]:
print(encoded_Y_test_CICBotIoT)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [118]:
argmax_Y_test_CICBotIoT = np.argmax(encoded_Y_test_CICBotIoT, axis=1)
print(argmax_Y_test_CICBotIoT)

[3 1 1 ... 3 3 1]


In [119]:
print(encoded_Y_test_CICBotIoT_w)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [120]:
argmax_Y_test_CICBotIoT_w = np.argmax(encoded_Y_test_CICBotIoT_w, axis=1)
print(argmax_Y_test_CICBotIoT_w)

[3 1 3 ... 1 3 3]


In [122]:
import numpy
from numpy import mean
from numpy import std
from numpy import array
from numpy import argmax

In [123]:
from numpy import tensordot
from numpy.linalg import norm
from itertools import product
from scipy.optimize import differential_evolution

In [124]:
def ensemble_predictions_weight(members, weights, testX):
    yhats = [model.predict(testX) for model in members]
    yhats = array(yhats)
    summed = tensordot(yhats, weights, axes=((0),(0)))
    result = argmax(summed, axis=1)
    return result

def evaluate_ensemble_weight(members, weights, testX, testy):
    yhat = ensemble_predictions_weight(members, weights, testX)
    return accuracy_score(testy, yhat)

def normalize(weights):
    result = norm(weights, 1)
    if result == 0.0:
        return weights
    return weights / result

def loss_function(weights, members, testX, testy):
    normalized = normalize(weights)
    return 1.0 - evaluate_ensemble_weight(members, normalized, testX, testy)

In [125]:
n_members_w = len(all_models)
bound_w = [(0.0, 1.0)  for _ in range(n_members_w)]

In [126]:
search_arg_CICIDS2017 = (all_models, X_CICIDS2017_test_w, argmax_Y_test_CICIDS2017_w)
result_ev_CICIDS2017 = differential_evolution(loss_function, bound_w, search_arg_CICIDS2017, maxiter=1, tol=1)
weights_pred_CICIDS2017 = normalize(result_ev_CICIDS2017['x'])

2401/2401 [==============================] - 3s 1ms/step


In [127]:
print('Optimized Weights CICIDS2017: %s' % weights_pred_CICIDS2017)

Optimized Weights CICIDS2017: [0.53750586 0.26430904 0.16936977 0.02881533]


In [128]:
pred_NN_weight_CICIDS2017 = ensemble_predictions_weight(all_models, weights_pred_CICIDS2017, X_CICIDS2017_test)

24002/24002 [==============================] - 43s 2ms/step


In [129]:
acc_pred_NN_weight_CICIDS2017 = accuracy_score(argmax_Y_test_CICIDS2017, pred_NN_weight_CICIDS2017)
print('Test Accuracy AVGNN Weighted CICIDS2017: %.3f' % acc_pred_NN_weight_CICIDS2017)
pre_mac_pred_NN_weight_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017, pred_NN_weight_CICIDS2017, average = 'macro')
print('Macro Test Precision AVGNN Weighted CICIDS2017: %.3f' % pre_mac_pred_NN_weight_CICIDS2017)
rec_mac_pred_NN_weight_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017, pred_NN_weight_CICIDS2017, average = 'macro')
print('Macro Test Recall AVGNN Weighted CICIDS2017: %.3f' % rec_mac_pred_NN_weight_CICIDS2017)
f1_mac_pred_NN_weight_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017, pred_NN_weight_CICIDS2017, average = 'macro')
print('Macro Test F1 AVGNN Weighted CICIDS2017: %.3f' % f1_mac_pred_NN_weight_CICIDS2017)
pre_mic_pred_NN_weight_CICIDS2017 = precision_score(argmax_Y_test_CICIDS2017, pred_NN_weight_CICIDS2017, average = 'micro')
print('Micro Test Precision AVGNN Weighted CICIDS2017: %.3f' % pre_mic_pred_NN_weight_CICIDS2017)
rec_mic_pred_NN_weight_CICIDS2017 = recall_score(argmax_Y_test_CICIDS2017, pred_NN_weight_CICIDS2017, average = 'micro')
print('Micro Test Recall AVGNN Weighted CICIDS2017: %.3f' % rec_mic_pred_NN_weight_CICIDS2017)
f1_mic_pred_NN_weight_CICIDS2017 = f1_score(argmax_Y_test_CICIDS2017, pred_NN_weight_CICIDS2017, average = 'micro')
print('Micro Test F1 AVGNN Weighted CICIDS2017: %.3f' % f1_mic_pred_NN_weight_CICIDS2017)

Test Accuracy AVGNN Weighted CICIDS2017: 0.986
Macro Test Precision AVGNN Weighted CICIDS2017: 0.908
Macro Test Recall AVGNN Weighted CICIDS2017: 0.759
Macro Test F1 AVGNN Weighted CICIDS2017: 0.753
Micro Test Precision AVGNN Weighted CICIDS2017: 0.986
Micro Test Recall AVGNN Weighted CICIDS2017: 0.986
Micro Test F1 AVGNN Weighted CICIDS2017: 0.986


In [130]:
search_arg_CICIDS2018 = (all_models, X_CICIDS2018_test_w, argmax_Y_test_CICIDS2018_w)
result_ev_CICIDS2018 = differential_evolution(loss_function, bound_w, search_arg_CICIDS2018, maxiter=1, tol=1)
weights_pred_CICIDS2018 = normalize(result_ev_CICIDS2018['x'])

 5848/14158 [===========>..................] - ETA: 13s

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



 3004/14158 [=====>........................] - ETA: 16s

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



 4968/14158 [=========>....................] - ETA: 15s

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



 7505/14158 [==============>...............] - ETA: 10s

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [132]:
print('Optimized Weights CICIDS2018: %s' % weights_pred_CICIDS2018)

Optimized Weights CICIDS2018: [0.28831444 0.37554657 0.05704304 0.27909594]


In [133]:
pred_NN_weight_CICIDS2018 = ensemble_predictions_weight(all_models, weights_pred_CICIDS2018, X_CICIDS2018_test)

141572/141572 [==============================] - 236s 2ms/step


In [134]:
acc_pred_NN_weight_CICIDS2018 = accuracy_score(argmax_Y_test_CICIDS2018, pred_NN_weight_CICIDS2018)
print('Test Accuracy AVGNN Weighted CICIDS2018: %.3f' % acc_pred_NN_weight_CICIDS2018)
pre_mac_pred_NN_weight_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018, pred_NN_weight_CICIDS2018, average = 'macro')
print('Macro Test Precision AVGNN Weighted CICIDS2018: %.3f' % pre_mac_pred_NN_weight_CICIDS2018)
rec_mac_pred_NN_weight_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018, pred_NN_weight_CICIDS2018, average = 'macro')
print('Macro Test Recall AVGNN Weighted CICIDS2018: %.3f' % rec_mac_pred_NN_weight_CICIDS2018)
f1_mac_pred_NN_weight_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018, pred_NN_weight_CICIDS2018, average = 'macro')
print('Macro Test F1 AVGNN Weighted CICIDS2018: %.3f' % f1_mac_pred_NN_weight_CICIDS2018)
pre_mic_pred_NN_weight_CICIDS2018 = precision_score(argmax_Y_test_CICIDS2018, pred_NN_weight_CICIDS2018, average = 'micro')
print('Micro Test Precision AVGNN Weighted CICIDS2018: %.3f' % pre_mic_pred_NN_weight_CICIDS2018)
rec_mic_pred_NN_weight_CICIDS2018 = recall_score(argmax_Y_test_CICIDS2018, pred_NN_weight_CICIDS2018, average = 'micro')
print('Micro Test Recall AVGNN Weighted CICIDS2018: %.3f' % rec_mic_pred_NN_weight_CICIDS2018)
f1_mic_pred_NN_weight_CICIDS2018 = f1_score(argmax_Y_test_CICIDS2018, pred_NN_weight_CICIDS2018, average = 'micro')
print('Micro Test F1 AVGNN Weighted CICIDS2018: %.3f' % f1_mic_pred_NN_weight_CICIDS2018)

Test Accuracy AVGNN Weighted CICIDS2018: 0.904
Macro Test Precision AVGNN Weighted CICIDS2018: 0.542
Macro Test Recall AVGNN Weighted CICIDS2018: 0.308
Macro Test F1 AVGNN Weighted CICIDS2018: 0.331
Micro Test Precision AVGNN Weighted CICIDS2018: 0.904
Micro Test Recall AVGNN Weighted CICIDS2018: 0.904
Micro Test F1 AVGNN Weighted CICIDS2018: 0.904


In [135]:
search_arg_CICToNIoT = (all_models, X_CICToNIoT_test_w, argmax_Y_test_CICToNIoT_w)
result_ev_CICToNIoT = differential_evolution(loss_function, bound_w, search_arg_CICToNIoT, maxiter=1, tol=1)
weights_pred_CICToNIoT = normalize(result_ev_CICToNIoT['x'])

2417/2417 [==============================] - 3s 1ms/step


In [136]:
print('Optimized Weights CICToNIoT: %s' % weights_pred_CICToNIoT)

Optimized Weights CICToNIoT: [0.38188757 0.05911294 0.53786483 0.02113466]


In [137]:
pred_NN_weight_CICToNIoT = ensemble_predictions_weight(all_models, weights_pred_CICToNIoT, X_CICToNIoT_test)

24166/24166 [==============================] - 38s 2ms/step


In [138]:
acc_pred_NN_weight_CICToNIoT = accuracy_score(argmax_Y_test_CICToNIoT, pred_NN_weight_CICToNIoT)
print('Test Accuracy AVGNN Weighted CICToNIoT: %.3f' % acc_pred_NN_weight_CICToNIoT)
pre_mac_pred_NN_weight_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT, pred_NN_weight_CICToNIoT, average = 'macro')
print('Macro Test Precision AVGNN Weighted CICToNIoT: %.3f' % pre_mac_pred_NN_weight_CICToNIoT)
rec_mac_pred_NN_weight_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT, pred_NN_weight_CICToNIoT, average = 'macro')
print('Macro Test Recall AVGNN Weighted CICToNIoT: %.3f' % rec_mac_pred_NN_weight_CICToNIoT)
f1_mac_pred_NN_weight_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT, pred_NN_weight_CICToNIoT, average = 'macro')
print('Macro Test F1 AVGNN Weighted CICToNIoT: %.3f' % f1_mac_pred_NN_weight_CICToNIoT)
pre_mic_pred_NN_weight_CICToNIoT = precision_score(argmax_Y_test_CICToNIoT, pred_NN_weight_CICToNIoT, average = 'micro')
print('Micro Test Precision AVGNN Weighted CICToNIoT: %.3f' % pre_mic_pred_NN_weight_CICToNIoT)
rec_mic_pred_NN_weight_CICToNIoT = recall_score(argmax_Y_test_CICToNIoT, pred_NN_weight_CICToNIoT, average = 'micro')
print('Micro Test Recall AVGNN Weighted CICToNIoT: %.3f' % rec_mic_pred_NN_weight_CICToNIoT)
f1_mic_pred_NN_weight_CICToNIoT = f1_score(argmax_Y_test_CICToNIoT, pred_NN_weight_CICToNIoT, average = 'micro')
print('Micro Test F1 AVGNN Weighted CICToNIoT: %.3f' % f1_mic_pred_NN_weight_CICToNIoT)

Test Accuracy AVGNN Weighted CICToNIoT: 0.989
Macro Test Precision AVGNN Weighted CICToNIoT: 0.847
Macro Test Recall AVGNN Weighted CICToNIoT: 0.755
Macro Test F1 AVGNN Weighted CICToNIoT: 0.790
Micro Test Precision AVGNN Weighted CICToNIoT: 0.989
Micro Test Recall AVGNN Weighted CICToNIoT: 0.989
Micro Test F1 AVGNN Weighted CICToNIoT: 0.989


In [139]:
search_arg_CICBotIoT = (all_models, X_CICBotIoT_test_w, argmax_Y_test_CICBotIoT_w)
result_ev_CICBotIoT = differential_evolution(loss_function, bound_w, search_arg_CICBotIoT, maxiter=1, tol=1)
weights_pred_CICBotIoT = normalize(result_ev_CICBotIoT['x'])

7986/7986 [==============================] - 10s 1ms/step


In [140]:
print('Optimized Weights CICBotIoT: %s' % weights_pred_CICBotIoT)

Optimized Weights CICBotIoT: [0.01722241 0.04268283 0.18829864 0.75179612]


In [141]:
pred_NN_weight_CICBotIoT = ensemble_predictions_weight(all_models, weights_pred_CICBotIoT, X_CICBotIoT_test)

79859/79859 [==============================] - 119s 1ms/step


In [142]:
acc_pred_NN_weight_CICBotIoT = accuracy_score(argmax_Y_test_CICBotIoT, pred_NN_weight_CICBotIoT)
print('Test Accuracy AVGNN Weighted CICBotIoT: %.3f' % acc_pred_NN_weight_CICBotIoT)
pre_mac_pred_NN_weight_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT, pred_NN_weight_CICBotIoT, average = 'macro')
print('Macro Test Precision AVGNN Weighted CICBotIoT: %.3f' % pre_mac_pred_NN_weight_CICBotIoT)
rec_mac_pred_NN_weight_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT, pred_NN_weight_CICBotIoT, average = 'macro')
print('Macro Test Recall AVGNN Weighted CICBotIoT: %.3f' % rec_mac_pred_NN_weight_CICBotIoT)
f1_mac_pred_NN_weight_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT, pred_NN_weight_CICBotIoT, average = 'macro')
print('Macro Test F1 AVGNN Weighted CICBotIoT: %.3f' % f1_mac_pred_NN_weight_CICBotIoT)
pre_mic_pred_NN_weight_CICBotIoT = precision_score(argmax_Y_test_CICBotIoT, pred_NN_weight_CICBotIoT, average = 'micro')
print('Micro Test Precision AVGNN Weighted CICBotIoT: %.3f' % pre_mic_pred_NN_weight_CICBotIoT)
rec_mic_pred_NN_weight_CICBotIoT = recall_score(argmax_Y_test_CICBotIoT, pred_NN_weight_CICBotIoT, average = 'micro')
print('Micro Test Recall AVGNN Weighted CICBotIoT: %.3f' % rec_mic_pred_NN_weight_CICBotIoT)
f1_mic_pred_NN_weight_CICBotIoT = f1_score(argmax_Y_test_CICBotIoT, pred_NN_weight_CICBotIoT, average = 'micro')
print('Micro Test F1 AVGNN Weighted CICBotIoT: %.3f' % f1_mic_pred_NN_weight_CICBotIoT)

Test Accuracy AVGNN Weighted CICBotIoT: 0.876
Macro Test Precision AVGNN Weighted CICBotIoT: 0.849
Macro Test Recall AVGNN Weighted CICBotIoT: 0.595
Macro Test F1 AVGNN Weighted CICBotIoT: 0.623
Micro Test Precision AVGNN Weighted CICBotIoT: 0.876
Micro Test Recall AVGNN Weighted CICBotIoT: 0.876
Micro Test F1 AVGNN Weighted CICBotIoT: 0.876
